version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mantonx"
    commit-message:
      prefix: "build"
      include: "scope"

  # Frontend npm packages
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly" 
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mantonx"
    commit-message:
      prefix: "build"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mantonx"
    commit-message:
      prefix: "build"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "mantonx"  
    commit-message:
      prefix: "ci"
      include: "scope"