run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis checks
    - unused        # Check for unused constants, variables, functions and types
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import formatting
    - misspell      # Find misspelled words
    - revive        # Replacement for golint
    - gosec         # Security-focused linter
    - goconst       # Find repeated strings that could be constants
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - shadow        # Shadow variable detection

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    # Enable all govet checks
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo
    
    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all
    
    # Exclude vendor directories
    - path: vendor/
      linters:
        - all

  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true