run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - misspell
  disable:
    - revive
    - gosec
    - goconst
    - gocyclo
    - dupl
    - gosimple
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: false
    disable:
      - fieldalignment
      - shadow
      - unusedwrite
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude stricter checks from tests and helper test code
    - path: _test\.go
      linters:
        - errcheck
        - govet
    - path: ^test/
      linters:
        - errcheck
        - govet
        - dupl
        - gocyclo
        - gosec
    # Exclude known WIP file from unused warnings (until implemented)
    - path: internal/database/metrics_repository\.go
      linters:
        - unused
    # Generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all
    # Vendor directories
    - path: vendor/
      linters:
        - all

  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
  print-linter-name: true
