// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertFilesParams struct {
	VolumeID    string             `json:"volume_id"`
	FolderID    pgtype.Int8        `json:"folder_id"`
	Path        string             `json:"path"`
	PathHash    []byte             `json:"path_hash"`
	Name        string             `json:"name"`
	Extension   pgtype.Text        `json:"extension"`
	Mime        pgtype.Text        `json:"mime"`
	SizeBytes   int64              `json:"size_bytes"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	AccessedAt  pgtype.Timestamptz `json:"accessed_at"`
	Mode        pgtype.Int4        `json:"mode"`
	OwnerUid    pgtype.Int4        `json:"owner_uid"`
	OwnerGid    pgtype.Int4        `json:"owner_gid"`
	ContentHash pgtype.Text        `json:"content_hash"`
	IsText      pgtype.Bool        `json:"is_text"`
	IsBinary    pgtype.Bool        `json:"is_binary"`
	MediaKind   pgtype.Text        `json:"media_kind"`
}

const countFilesByFolder = `-- name: CountFilesByFolder :one
SELECT COUNT(*) FROM files WHERE folder_id = $1
`

func (q *Queries) CountFilesByFolder(ctx context.Context, folderID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByVolume = `-- name: CountFilesByVolume :one
SELECT COUNT(*) FROM files WHERE volume_id = $1
`

func (q *Queries) CountFilesByVolume(ctx context.Context, volumeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByVolume, volumeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOldFiles = `-- name: CountOldFiles :one
SELECT COUNT(*) FROM files 
WHERE last_scan_at < $1
  AND last_scan_at IS NOT NULL
`

func (q *Queries) CountOldFiles(ctx context.Context, lastScanAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countOldFiles, lastScanAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    volume_id, folder_id, path, path_hash, name, extension, mime, 
    size_bytes, modified_at, accessed_at, mode, owner_uid, owner_gid, 
    content_hash, is_text, is_binary, media_kind
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 
    $8, $9, $10, $11, $12, $13, 
    $14, $15, $16, $17
) RETURNING id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id
`

type CreateFileParams struct {
	VolumeID    string             `json:"volume_id"`
	FolderID    pgtype.Int8        `json:"folder_id"`
	Path        string             `json:"path"`
	PathHash    []byte             `json:"path_hash"`
	Name        string             `json:"name"`
	Extension   pgtype.Text        `json:"extension"`
	Mime        pgtype.Text        `json:"mime"`
	SizeBytes   int64              `json:"size_bytes"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	AccessedAt  pgtype.Timestamptz `json:"accessed_at"`
	Mode        pgtype.Int4        `json:"mode"`
	OwnerUid    pgtype.Int4        `json:"owner_uid"`
	OwnerGid    pgtype.Int4        `json:"owner_gid"`
	ContentHash pgtype.Text        `json:"content_hash"`
	IsText      pgtype.Bool        `json:"is_text"`
	IsBinary    pgtype.Bool        `json:"is_binary"`
	MediaKind   pgtype.Text        `json:"media_kind"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (Files, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.VolumeID,
		arg.FolderID,
		arg.Path,
		arg.PathHash,
		arg.Name,
		arg.Extension,
		arg.Mime,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.AccessedAt,
		arg.Mode,
		arg.OwnerUid,
		arg.OwnerGid,
		arg.ContentHash,
		arg.IsText,
		arg.IsBinary,
		arg.MediaKind,
	)
	var i Files
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.FolderID,
		&i.Path,
		&i.PathHash,
		&i.Name,
		&i.Extension,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AccessedAt,
		&i.Mode,
		&i.OwnerUid,
		&i.OwnerGid,
		&i.ContentHash,
		&i.IsText,
		&i.IsBinary,
		&i.MediaKind,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.ColorPrimaries,
		&i.TransferCharacteristic,
		&i.HdrFormat,
		&i.CaptureDatetime,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.SubtitleLanguage,
		&i.SubtitleFormat,
		&i.CueCount,
		&i.CoveragePercent,
		&i.AudioChannels,
		&i.AudioCodec,
		&i.AudioSampleRate,
		&i.VideoCodec,
		&i.VideoProfile,
		&i.VideoLevel,
		&i.FirstSeenAt,
		&i.LastScanAt,
		&i.OrganizationID,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFilesByVolume = `-- name: DeleteFilesByVolume :exec
DELETE FROM files WHERE volume_id = $1
`

func (q *Queries) DeleteFilesByVolume(ctx context.Context, volumeID string) error {
	_, err := q.db.Exec(ctx, deleteFilesByVolume, volumeID)
	return err
}

const deleteOldFiles = `-- name: DeleteOldFiles :exec
DELETE FROM files 
WHERE last_scan_at < $1
  AND last_scan_at IS NOT NULL
`

// Retention queries for cleanup
func (q *Queries) DeleteOldFiles(ctx context.Context, lastScanAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldFiles, lastScanAt)
	return err
}

const getDistinctExtensions = `-- name: GetDistinctExtensions :many
SELECT extension, COUNT(*) as count
FROM files 
WHERE volume_id = $1 AND extension IS NOT NULL
GROUP BY extension
ORDER BY count DESC
LIMIT $2
`

type GetDistinctExtensionsParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
}

type GetDistinctExtensionsRow struct {
	Extension pgtype.Text `json:"extension"`
	Count     int64       `json:"count"`
}

func (q *Queries) GetDistinctExtensions(ctx context.Context, arg GetDistinctExtensionsParams) ([]GetDistinctExtensionsRow, error) {
	rows, err := q.db.Query(ctx, getDistinctExtensions, arg.VolumeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctExtensionsRow{}
	for rows.Next() {
		var i GetDistinctExtensionsRow
		if err := rows.Scan(&i.Extension, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctMediaKinds = `-- name: GetDistinctMediaKinds :many
SELECT media_kind, COUNT(*) as count
FROM files 
WHERE volume_id = $1 AND media_kind IS NOT NULL
GROUP BY media_kind
ORDER BY count DESC
`

type GetDistinctMediaKindsRow struct {
	MediaKind pgtype.Text `json:"media_kind"`
	Count     int64       `json:"count"`
}

func (q *Queries) GetDistinctMediaKinds(ctx context.Context, volumeID string) ([]GetDistinctMediaKindsRow, error) {
	rows, err := q.db.Query(ctx, getDistinctMediaKinds, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctMediaKindsRow{}
	for rows.Next() {
		var i GetDistinctMediaKindsRow
		if err := rows.Scan(&i.MediaKind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctMimeTypes = `-- name: GetDistinctMimeTypes :many
SELECT mime as mime_type, COUNT(*) as count
FROM files 
WHERE volume_id = $1 AND mime IS NOT NULL
GROUP BY mime
ORDER BY count DESC
`

type GetDistinctMimeTypesRow struct {
	MimeType pgtype.Text `json:"mime_type"`
	Count    int64       `json:"count"`
}

func (q *Queries) GetDistinctMimeTypes(ctx context.Context, volumeID string) ([]GetDistinctMimeTypesRow, error) {
	rows, err := q.db.Query(ctx, getDistinctMimeTypes, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctMimeTypesRow{}
	for rows.Next() {
		var i GetDistinctMimeTypesRow
		if err := rows.Scan(&i.MimeType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicateFiles = `-- name: GetDuplicateFiles :many
SELECT files.id, files.volume_id, files.folder_id, files.path, files.path_hash, files.name, files.extension, files.mime, files.size_bytes, files.created_at, files.modified_at, files.accessed_at, files.mode, files.owner_uid, files.owner_gid, files.content_hash, files.is_text, files.is_binary, files.media_kind, files.duration_ms, files.bitrate_kbps, files.width, files.height, files.fps, files.color_primaries, files.transfer_characteristic, files.hdr_format, files.capture_datetime, files.camera_make, files.camera_model, files.lens_model, files.orientation, files.gps_latitude, files.gps_longitude, files.subtitle_language, files.subtitle_format, files.cue_count, files.coverage_percent, files.audio_channels, files.audio_codec, files.audio_sample_rate, files.video_codec, files.video_profile, files.video_level, files.first_seen_at, files.last_scan_at, files.organization_id FROM files WHERE files.volume_id = $1 AND files.content_hash IS NOT NULL AND files.content_hash IN (
    SELECT f.content_hash FROM files f WHERE f.volume_id = $1 AND f.content_hash IS NOT NULL
    GROUP BY f.content_hash HAVING COUNT(*) > 1
) ORDER BY files.content_hash, files.path
`

func (q *Queries) GetDuplicateFiles(ctx context.Context, volumeID string) ([]Files, error) {
	rows, err := q.db.Query(ctx, getDuplicateFiles, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicateFilesBySize = `-- name: GetDuplicateFilesBySize :many
SELECT size_bytes, COUNT(*) as count, array_agg(path) as paths
FROM files 
WHERE volume_id = $1 AND size_bytes > 0
GROUP BY size_bytes
HAVING COUNT(*) > 1
ORDER BY size_bytes DESC
LIMIT $2
`

type GetDuplicateFilesBySizeParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
}

type GetDuplicateFilesBySizeRow struct {
	SizeBytes int64       `json:"size_bytes"`
	Count     int64       `json:"count"`
	Paths     interface{} `json:"paths"`
}

func (q *Queries) GetDuplicateFilesBySize(ctx context.Context, arg GetDuplicateFilesBySizeParams) ([]GetDuplicateFilesBySizeRow, error) {
	rows, err := q.db.Query(ctx, getDuplicateFilesBySize, arg.VolumeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDuplicateFilesBySizeRow{}
	for rows.Next() {
		var i GetDuplicateFilesBySizeRow
		if err := rows.Scan(&i.SizeBytes, &i.Count, &i.Paths); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicateFilesContent = `-- name: GetDuplicateFilesContent :many
SELECT files.id, files.volume_id, files.folder_id, files.path, files.path_hash, files.name, files.extension, files.mime, files.size_bytes, files.created_at, files.modified_at, files.accessed_at, files.mode, files.owner_uid, files.owner_gid, files.content_hash, files.is_text, files.is_binary, files.media_kind, files.duration_ms, files.bitrate_kbps, files.width, files.height, files.fps, files.color_primaries, files.transfer_characteristic, files.hdr_format, files.capture_datetime, files.camera_make, files.camera_model, files.lens_model, files.orientation, files.gps_latitude, files.gps_longitude, files.subtitle_language, files.subtitle_format, files.cue_count, files.coverage_percent, files.audio_channels, files.audio_codec, files.audio_sample_rate, files.video_codec, files.video_profile, files.video_level, files.first_seen_at, files.last_scan_at, files.organization_id FROM files WHERE files.volume_id = $1 AND files.content_hash IS NOT NULL AND files.content_hash IN (
    SELECT f.content_hash FROM files f WHERE f.volume_id = $1 AND f.content_hash IS NOT NULL
    GROUP BY f.content_hash HAVING COUNT(*) > 1
) ORDER BY files.content_hash, files.path
`

func (q *Queries) GetDuplicateFilesContent(ctx context.Context, volumeID string) ([]Files, error) {
	rows, err := q.db.Query(ctx, getDuplicateFilesContent, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExtensionStats = `-- name: GetExtensionStats :many
SELECT 
    extension,
    COUNT(*) as file_count,
    COALESCE(SUM(size_bytes), 0) as total_size,
    COALESCE(AVG(size_bytes), 0) as avg_size
FROM files 
WHERE volume_id = $1 AND extension IS NOT NULL
GROUP BY extension
ORDER BY file_count DESC
LIMIT $2
`

type GetExtensionStatsParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
}

type GetExtensionStatsRow struct {
	Extension pgtype.Text `json:"extension"`
	FileCount int64       `json:"file_count"`
	TotalSize interface{} `json:"total_size"`
	AvgSize   interface{} `json:"avg_size"`
}

func (q *Queries) GetExtensionStats(ctx context.Context, arg GetExtensionStatsParams) ([]GetExtensionStatsRow, error) {
	rows, err := q.db.Query(ctx, getExtensionStats, arg.VolumeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExtensionStatsRow{}
	for rows.Next() {
		var i GetExtensionStatsRow
		if err := rows.Scan(
			&i.Extension,
			&i.FileCount,
			&i.TotalSize,
			&i.AvgSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (Files, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i Files
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.FolderID,
		&i.Path,
		&i.PathHash,
		&i.Name,
		&i.Extension,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AccessedAt,
		&i.Mode,
		&i.OwnerUid,
		&i.OwnerGid,
		&i.ContentHash,
		&i.IsText,
		&i.IsBinary,
		&i.MediaKind,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.ColorPrimaries,
		&i.TransferCharacteristic,
		&i.HdrFormat,
		&i.CaptureDatetime,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.SubtitleLanguage,
		&i.SubtitleFormat,
		&i.CueCount,
		&i.CoveragePercent,
		&i.AudioChannels,
		&i.AudioCodec,
		&i.AudioSampleRate,
		&i.VideoCodec,
		&i.VideoProfile,
		&i.VideoLevel,
		&i.FirstSeenAt,
		&i.LastScanAt,
		&i.OrganizationID,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one

SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE id = $1
`

// File management queries for PostgreSQL
func (q *Queries) GetFileByID(ctx context.Context, id int64) (Files, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i Files
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.FolderID,
		&i.Path,
		&i.PathHash,
		&i.Name,
		&i.Extension,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AccessedAt,
		&i.Mode,
		&i.OwnerUid,
		&i.OwnerGid,
		&i.ContentHash,
		&i.IsText,
		&i.IsBinary,
		&i.MediaKind,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.ColorPrimaries,
		&i.TransferCharacteristic,
		&i.HdrFormat,
		&i.CaptureDatetime,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.SubtitleLanguage,
		&i.SubtitleFormat,
		&i.CueCount,
		&i.CoveragePercent,
		&i.AudioChannels,
		&i.AudioCodec,
		&i.AudioSampleRate,
		&i.VideoCodec,
		&i.VideoProfile,
		&i.VideoLevel,
		&i.FirstSeenAt,
		&i.LastScanAt,
		&i.OrganizationID,
	)
	return i, err
}

const getFileByPath = `-- name: GetFileByPath :one
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE volume_id = $1 AND path = $2
`

type GetFileByPathParams struct {
	VolumeID string `json:"volume_id"`
	Path     string `json:"path"`
}

func (q *Queries) GetFileByPath(ctx context.Context, arg GetFileByPathParams) (Files, error) {
	row := q.db.QueryRow(ctx, getFileByPath, arg.VolumeID, arg.Path)
	var i Files
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.FolderID,
		&i.Path,
		&i.PathHash,
		&i.Name,
		&i.Extension,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AccessedAt,
		&i.Mode,
		&i.OwnerUid,
		&i.OwnerGid,
		&i.ContentHash,
		&i.IsText,
		&i.IsBinary,
		&i.MediaKind,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.ColorPrimaries,
		&i.TransferCharacteristic,
		&i.HdrFormat,
		&i.CaptureDatetime,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.SubtitleLanguage,
		&i.SubtitleFormat,
		&i.CueCount,
		&i.CoveragePercent,
		&i.AudioChannels,
		&i.AudioCodec,
		&i.AudioSampleRate,
		&i.VideoCodec,
		&i.VideoProfile,
		&i.VideoLevel,
		&i.FirstSeenAt,
		&i.LastScanAt,
		&i.OrganizationID,
	)
	return i, err
}

const getFileStats = `-- name: GetFileStats :one
SELECT 
    COUNT(*) as total_files,
    COALESCE(SUM(size_bytes), 0) as total_size,
    COALESCE(AVG(size_bytes), 0) as avg_file_size,
    COALESCE(MAX(size_bytes), 0) as largest_file,
    COUNT(DISTINCT extension) as unique_extensions,
    COUNT(DISTINCT media_kind) as unique_media_kinds,
    COUNT(content_hash) as hashed_files
FROM files WHERE volume_id = $1
`

type GetFileStatsRow struct {
	TotalFiles       int64       `json:"total_files"`
	TotalSize        interface{} `json:"total_size"`
	AvgFileSize      interface{} `json:"avg_file_size"`
	LargestFile      interface{} `json:"largest_file"`
	UniqueExtensions int64       `json:"unique_extensions"`
	UniqueMediaKinds int64       `json:"unique_media_kinds"`
	HashedFiles      int64       `json:"hashed_files"`
}

func (q *Queries) GetFileStats(ctx context.Context, volumeID string) (GetFileStatsRow, error) {
	row := q.db.QueryRow(ctx, getFileStats, volumeID)
	var i GetFileStatsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.TotalSize,
		&i.AvgFileSize,
		&i.LargestFile,
		&i.UniqueExtensions,
		&i.UniqueMediaKinds,
		&i.HashedFiles,
	)
	return i, err
}

const getFilesByExtension = `-- name: GetFilesByExtension :many
SELECT extension, COUNT(*) as count, COALESCE(SUM(size_bytes), 0) as total_size
FROM files 
WHERE volume_id = $1 AND extension IS NOT NULL
GROUP BY extension
ORDER BY count DESC
LIMIT $2
`

type GetFilesByExtensionParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
}

type GetFilesByExtensionRow struct {
	Extension pgtype.Text `json:"extension"`
	Count     int64       `json:"count"`
	TotalSize interface{} `json:"total_size"`
}

func (q *Queries) GetFilesByExtension(ctx context.Context, arg GetFilesByExtensionParams) ([]GetFilesByExtensionRow, error) {
	rows, err := q.db.Query(ctx, getFilesByExtension, arg.VolumeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFilesByExtensionRow{}
	for rows.Next() {
		var i GetFilesByExtensionRow
		if err := rows.Scan(&i.Extension, &i.Count, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByExtensionFiles = `-- name: GetFilesByExtensionFiles :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files
WHERE volume_id = $1 AND extension = $2
ORDER BY path
LIMIT $3 OFFSET $4
`

type GetFilesByExtensionFilesParams struct {
	VolumeID  string      `json:"volume_id"`
	Extension pgtype.Text `json:"extension"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetFilesByExtensionFiles(ctx context.Context, arg GetFilesByExtensionFilesParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, getFilesByExtensionFiles,
		arg.VolumeID,
		arg.Extension,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByMediaKind = `-- name: GetFilesByMediaKind :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files
WHERE volume_id = $1 AND media_kind = $2
ORDER BY path
LIMIT $3 OFFSET $4
`

type GetFilesByMediaKindParams struct {
	VolumeID  string      `json:"volume_id"`
	MediaKind pgtype.Text `json:"media_kind"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetFilesByMediaKind(ctx context.Context, arg GetFilesByMediaKindParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, getFilesByMediaKind,
		arg.VolumeID,
		arg.MediaKind,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByMimeType = `-- name: GetFilesByMimeType :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files
WHERE volume_id = $1 AND mime = $2
ORDER BY path
LIMIT $3 OFFSET $4
`

type GetFilesByMimeTypeParams struct {
	VolumeID string      `json:"volume_id"`
	Mime     pgtype.Text `json:"mime"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetFilesByMimeType(ctx context.Context, arg GetFilesByMimeTypeParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, getFilesByMimeType,
		arg.VolumeID,
		arg.Mime,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesBySize = `-- name: GetFilesBySize :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE volume_id = $1 AND size_bytes BETWEEN $2 AND $3 ORDER BY size_bytes DESC LIMIT $4
`

type GetFilesBySizeParams struct {
	VolumeID    string `json:"volume_id"`
	SizeBytes   int64  `json:"size_bytes"`
	SizeBytes_2 int64  `json:"size_bytes_2"`
	Limit       int32  `json:"limit"`
}

func (q *Queries) GetFilesBySize(ctx context.Context, arg GetFilesBySizeParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, getFilesBySize,
		arg.VolumeID,
		arg.SizeBytes,
		arg.SizeBytes_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesModifiedSince = `-- name: GetFilesModifiedSince :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE volume_id = $1 AND modified_at >= $2 ORDER BY modified_at DESC
`

type GetFilesModifiedSinceParams struct {
	VolumeID   string             `json:"volume_id"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
}

func (q *Queries) GetFilesModifiedSince(ctx context.Context, arg GetFilesModifiedSinceParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, getFilesModifiedSince, arg.VolumeID, arg.ModifiedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLargestFiles = `-- name: GetLargestFiles :many
SELECT id, volume_id, path, name, size_bytes, modified_at
FROM files 
WHERE volume_id = $1
ORDER BY size_bytes DESC
LIMIT $2
`

type GetLargestFilesParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
}

type GetLargestFilesRow struct {
	ID         int64              `json:"id"`
	VolumeID   string             `json:"volume_id"`
	Path       string             `json:"path"`
	Name       string             `json:"name"`
	SizeBytes  int64              `json:"size_bytes"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
}

func (q *Queries) GetLargestFiles(ctx context.Context, arg GetLargestFilesParams) ([]GetLargestFilesRow, error) {
	rows, err := q.db.Query(ctx, getLargestFiles, arg.VolumeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLargestFilesRow{}
	for rows.Next() {
		var i GetLargestFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.Path,
			&i.Name,
			&i.SizeBytes,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaKindStats = `-- name: GetMediaKindStats :many
SELECT 
    media_kind,
    COUNT(*) as file_count,
    COALESCE(SUM(size_bytes), 0) as total_size,
    COALESCE(AVG(size_bytes), 0) as avg_size
FROM files 
WHERE volume_id = $1 AND media_kind IS NOT NULL
GROUP BY media_kind
ORDER BY file_count DESC
`

type GetMediaKindStatsRow struct {
	MediaKind pgtype.Text `json:"media_kind"`
	FileCount int64       `json:"file_count"`
	TotalSize interface{} `json:"total_size"`
	AvgSize   interface{} `json:"avg_size"`
}

func (q *Queries) GetMediaKindStats(ctx context.Context, volumeID string) ([]GetMediaKindStatsRow, error) {
	rows, err := q.db.Query(ctx, getMediaKindStats, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaKindStatsRow{}
	for rows.Next() {
		var i GetMediaKindStatsRow
		if err := rows.Scan(
			&i.MediaKind,
			&i.FileCount,
			&i.TotalSize,
			&i.AvgSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentFiles = `-- name: GetRecentFiles :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE volume_id = $1 AND modified_at >= $2 ORDER BY modified_at DESC LIMIT $3
`

type GetRecentFilesParams struct {
	VolumeID   string             `json:"volume_id"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) GetRecentFiles(ctx context.Context, arg GetRecentFilesParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, getRecentFiles, arg.VolumeID, arg.ModifiedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSizeByVolume = `-- name: GetTotalSizeByVolume :one
SELECT COALESCE(SUM(size_bytes), 0) as total_size FROM files WHERE volume_id = $1
`

func (q *Queries) GetTotalSizeByVolume(ctx context.Context, volumeID string) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalSizeByVolume, volumeID)
	var total_size interface{}
	err := row.Scan(&total_size)
	return total_size, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files 
WHERE volume_id = $1
ORDER BY path
LIMIT $2 OFFSET $3
`

type ListFilesParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByFolder = `-- name: ListFilesByFolder :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE folder_id = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListFilesByFolderParams struct {
	FolderID pgtype.Int8 `json:"folder_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListFilesByFolder(ctx context.Context, arg ListFilesByFolderParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, listFilesByFolder, arg.FolderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByVolume = `-- name: ListFilesByVolume :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE volume_id = $1 ORDER BY path LIMIT $2 OFFSET $3
`

type ListFilesByVolumeParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListFilesByVolume(ctx context.Context, arg ListFilesByVolumeParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, listFilesByVolume, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByVolumeAndOrganization = `-- name: ListFilesByVolumeAndOrganization :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files WHERE volume_id = $1 AND organization_id = $2 ORDER BY path LIMIT $3 OFFSET $4
`

type ListFilesByVolumeAndOrganizationParams struct {
	VolumeID       string      `json:"volume_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListFilesByVolumeAndOrganization(ctx context.Context, arg ListFilesByVolumeAndOrganizationParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, listFilesByVolumeAndOrganization,
		arg.VolumeID,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFilesByName = `-- name: SearchFilesByName :many
SELECT id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id FROM files
WHERE volume_id = $1 AND name ILIKE '%' || $2 || '%'
ORDER BY name
LIMIT $3 OFFSET $4
`

type SearchFilesByNameParams struct {
	VolumeID string      `json:"volume_id"`
	Column2  pgtype.Text `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) SearchFilesByName(ctx context.Context, arg SearchFilesByNameParams) ([]Files, error) {
	rows, err := q.db.Query(ctx, searchFilesByName,
		arg.VolumeID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Files{}
	for rows.Next() {
		var i Files
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.FolderID,
			&i.Path,
			&i.PathHash,
			&i.Name,
			&i.Extension,
			&i.Mime,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.AccessedAt,
			&i.Mode,
			&i.OwnerUid,
			&i.OwnerGid,
			&i.ContentHash,
			&i.IsText,
			&i.IsBinary,
			&i.MediaKind,
			&i.DurationMs,
			&i.BitrateKbps,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.ColorPrimaries,
			&i.TransferCharacteristic,
			&i.HdrFormat,
			&i.CaptureDatetime,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.SubtitleLanguage,
			&i.SubtitleFormat,
			&i.CueCount,
			&i.CoveragePercent,
			&i.AudioChannels,
			&i.AudioCodec,
			&i.AudioSampleRate,
			&i.VideoCodec,
			&i.VideoProfile,
			&i.VideoLevel,
			&i.FirstSeenAt,
			&i.LastScanAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFile = `-- name: UpdateFile :one
UPDATE files 
SET 
    size_bytes = $2,
    modified_at = $3,
    accessed_at = $4,
    content_hash = $5,
    last_scan_at = NOW()
WHERE id = $1
RETURNING id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id
`

type UpdateFileParams struct {
	ID          int64              `json:"id"`
	SizeBytes   int64              `json:"size_bytes"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	AccessedAt  pgtype.Timestamptz `json:"accessed_at"`
	ContentHash pgtype.Text        `json:"content_hash"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (Files, error) {
	row := q.db.QueryRow(ctx, updateFile,
		arg.ID,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.AccessedAt,
		arg.ContentHash,
	)
	var i Files
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.FolderID,
		&i.Path,
		&i.PathHash,
		&i.Name,
		&i.Extension,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AccessedAt,
		&i.Mode,
		&i.OwnerUid,
		&i.OwnerGid,
		&i.ContentHash,
		&i.IsText,
		&i.IsBinary,
		&i.MediaKind,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.ColorPrimaries,
		&i.TransferCharacteristic,
		&i.HdrFormat,
		&i.CaptureDatetime,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.SubtitleLanguage,
		&i.SubtitleFormat,
		&i.CueCount,
		&i.CoveragePercent,
		&i.AudioChannels,
		&i.AudioCodec,
		&i.AudioSampleRate,
		&i.VideoCodec,
		&i.VideoProfile,
		&i.VideoLevel,
		&i.FirstSeenAt,
		&i.LastScanAt,
		&i.OrganizationID,
	)
	return i, err
}

const updateFileHash = `-- name: UpdateFileHash :exec
UPDATE files SET content_hash = $2 WHERE id = $1
`

type UpdateFileHashParams struct {
	ID          int64       `json:"id"`
	ContentHash pgtype.Text `json:"content_hash"`
}

func (q *Queries) UpdateFileHash(ctx context.Context, arg UpdateFileHashParams) error {
	_, err := q.db.Exec(ctx, updateFileHash, arg.ID, arg.ContentHash)
	return err
}

const updateFileMime = `-- name: UpdateFileMime :exec
UPDATE files SET 
    mime = $2,
    media_kind = $3,
    is_text = $4,
    is_binary = $5
WHERE id = $1
`

type UpdateFileMimeParams struct {
	ID        int64       `json:"id"`
	Mime      pgtype.Text `json:"mime"`
	MediaKind pgtype.Text `json:"media_kind"`
	IsText    pgtype.Bool `json:"is_text"`
	IsBinary  pgtype.Bool `json:"is_binary"`
}

func (q *Queries) UpdateFileMime(ctx context.Context, arg UpdateFileMimeParams) error {
	_, err := q.db.Exec(ctx, updateFileMime,
		arg.ID,
		arg.Mime,
		arg.MediaKind,
		arg.IsText,
		arg.IsBinary,
	)
	return err
}

const updateFileSystemMetadata = `-- name: UpdateFileSystemMetadata :exec
UPDATE files SET 
    size_bytes = $2,
    modified_at = $3,
    accessed_at = $4,
    mode = $5,
    owner_uid = $6,
    owner_gid = $7
WHERE id = $1
`

type UpdateFileSystemMetadataParams struct {
	ID         int64              `json:"id"`
	SizeBytes  int64              `json:"size_bytes"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
	Mode       pgtype.Int4        `json:"mode"`
	OwnerUid   pgtype.Int4        `json:"owner_uid"`
	OwnerGid   pgtype.Int4        `json:"owner_gid"`
}

func (q *Queries) UpdateFileSystemMetadata(ctx context.Context, arg UpdateFileSystemMetadataParams) error {
	_, err := q.db.Exec(ctx, updateFileSystemMetadata,
		arg.ID,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.AccessedAt,
		arg.Mode,
		arg.OwnerUid,
		arg.OwnerGid,
	)
	return err
}

const upsertFile = `-- name: UpsertFile :one
INSERT INTO files (
    volume_id, folder_id, path, path_hash, name, extension, mime, 
    size_bytes, modified_at, accessed_at, mode, owner_uid, owner_gid, 
    content_hash, is_text, is_binary, media_kind, organization_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 
    $8, $9, $10, $11, $12, $13, 
    $14, $15, $16, $17, $18
) ON CONFLICT (volume_id, path_hash) DO UPDATE SET
    folder_id = EXCLUDED.folder_id,
    name = EXCLUDED.name,
    extension = EXCLUDED.extension,
    mime = EXCLUDED.mime,
    size_bytes = EXCLUDED.size_bytes,
    modified_at = EXCLUDED.modified_at,
    accessed_at = EXCLUDED.accessed_at,
    mode = EXCLUDED.mode,
    owner_uid = EXCLUDED.owner_uid,
    owner_gid = EXCLUDED.owner_gid,
    content_hash = EXCLUDED.content_hash,
    is_text = EXCLUDED.is_text,
    is_binary = EXCLUDED.is_binary,
    media_kind = EXCLUDED.media_kind,
    organization_id = EXCLUDED.organization_id
RETURNING id, volume_id, folder_id, path, path_hash, name, extension, mime, size_bytes, created_at, modified_at, accessed_at, mode, owner_uid, owner_gid, content_hash, is_text, is_binary, media_kind, duration_ms, bitrate_kbps, width, height, fps, color_primaries, transfer_characteristic, hdr_format, capture_datetime, camera_make, camera_model, lens_model, orientation, gps_latitude, gps_longitude, subtitle_language, subtitle_format, cue_count, coverage_percent, audio_channels, audio_codec, audio_sample_rate, video_codec, video_profile, video_level, first_seen_at, last_scan_at, organization_id
`

type UpsertFileParams struct {
	VolumeID       string             `json:"volume_id"`
	FolderID       pgtype.Int8        `json:"folder_id"`
	Path           string             `json:"path"`
	PathHash       []byte             `json:"path_hash"`
	Name           string             `json:"name"`
	Extension      pgtype.Text        `json:"extension"`
	Mime           pgtype.Text        `json:"mime"`
	SizeBytes      int64              `json:"size_bytes"`
	ModifiedAt     pgtype.Timestamptz `json:"modified_at"`
	AccessedAt     pgtype.Timestamptz `json:"accessed_at"`
	Mode           pgtype.Int4        `json:"mode"`
	OwnerUid       pgtype.Int4        `json:"owner_uid"`
	OwnerGid       pgtype.Int4        `json:"owner_gid"`
	ContentHash    pgtype.Text        `json:"content_hash"`
	IsText         pgtype.Bool        `json:"is_text"`
	IsBinary       pgtype.Bool        `json:"is_binary"`
	MediaKind      pgtype.Text        `json:"media_kind"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) (Files, error) {
	row := q.db.QueryRow(ctx, upsertFile,
		arg.VolumeID,
		arg.FolderID,
		arg.Path,
		arg.PathHash,
		arg.Name,
		arg.Extension,
		arg.Mime,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.AccessedAt,
		arg.Mode,
		arg.OwnerUid,
		arg.OwnerGid,
		arg.ContentHash,
		arg.IsText,
		arg.IsBinary,
		arg.MediaKind,
		arg.OrganizationID,
	)
	var i Files
	err := row.Scan(
		&i.ID,
		&i.VolumeID,
		&i.FolderID,
		&i.Path,
		&i.PathHash,
		&i.Name,
		&i.Extension,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.AccessedAt,
		&i.Mode,
		&i.OwnerUid,
		&i.OwnerGid,
		&i.ContentHash,
		&i.IsText,
		&i.IsBinary,
		&i.MediaKind,
		&i.DurationMs,
		&i.BitrateKbps,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.ColorPrimaries,
		&i.TransferCharacteristic,
		&i.HdrFormat,
		&i.CaptureDatetime,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.SubtitleLanguage,
		&i.SubtitleFormat,
		&i.CueCount,
		&i.CoveragePercent,
		&i.AudioChannels,
		&i.AudioCodec,
		&i.AudioSampleRate,
		&i.VideoCodec,
		&i.VideoProfile,
		&i.VideoLevel,
		&i.FirstSeenAt,
		&i.LastScanAt,
		&i.OrganizationID,
	)
	return i, err
}
