// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metadata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDistinctExtensions = `-- name: GetDistinctExtensions :many
SELECT DISTINCT extension, COUNT(*) as file_count
FROM files 
WHERE extension IS NOT NULL AND extension != ''
GROUP BY extension
ORDER BY file_count DESC, extension ASC
LIMIT 50
`

type GetDistinctExtensionsRow struct {
	Extension pgtype.Text `json:"extension"`
	FileCount int64       `json:"file_count"`
}

func (q *Queries) GetDistinctExtensions(ctx context.Context) ([]GetDistinctExtensionsRow, error) {
	rows, err := q.db.Query(ctx, getDistinctExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctExtensionsRow{}
	for rows.Next() {
		var i GetDistinctExtensionsRow
		if err := rows.Scan(&i.Extension, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctMediaKinds = `-- name: GetDistinctMediaKinds :many
SELECT DISTINCT media_kind, COUNT(*) as file_count
FROM files 
WHERE media_kind IS NOT NULL AND media_kind != ''
GROUP BY media_kind
ORDER BY file_count DESC, media_kind ASC
`

type GetDistinctMediaKindsRow struct {
	MediaKind pgtype.Text `json:"media_kind"`
	FileCount int64       `json:"file_count"`
}

func (q *Queries) GetDistinctMediaKinds(ctx context.Context) ([]GetDistinctMediaKindsRow, error) {
	rows, err := q.db.Query(ctx, getDistinctMediaKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctMediaKindsRow{}
	for rows.Next() {
		var i GetDistinctMediaKindsRow
		if err := rows.Scan(&i.MediaKind, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctMimeTypes = `-- name: GetDistinctMimeTypes :many

SELECT DISTINCT mime AS mime_type, COUNT(*) as file_count
FROM files 
WHERE mime IS NOT NULL AND mime != ''
GROUP BY mime
ORDER BY file_count DESC, mime ASC
`

type GetDistinctMimeTypesRow struct {
	MimeType  pgtype.Text `json:"mime_type"`
	FileCount int64       `json:"file_count"`
}

// Metadata Queries
// Get distinct values for filter dropdowns
func (q *Queries) GetDistinctMimeTypes(ctx context.Context) ([]GetDistinctMimeTypesRow, error) {
	rows, err := q.db.Query(ctx, getDistinctMimeTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDistinctMimeTypesRow{}
	for rows.Next() {
		var i GetDistinctMimeTypesRow
		if err := rows.Scan(&i.MimeType, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
