// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MountAccessMode string

const (
	MountAccessModeRw MountAccessMode = "rw"
	MountAccessModeRo MountAccessMode = "ro"
)

func (e *MountAccessMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MountAccessMode(s)
	case string:
		*e = MountAccessMode(s)
	default:
		return fmt.Errorf("unsupported scan type for MountAccessMode: %T", src)
	}
	return nil
}

type NullMountAccessMode struct {
	MountAccessMode MountAccessMode `json:"mount_access_mode"`
	Valid           bool            `json:"valid"` // Valid is true if MountAccessMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMountAccessMode) Scan(value interface{}) error {
	if value == nil {
		ns.MountAccessMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MountAccessMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMountAccessMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MountAccessMode), nil
}

func AllMountAccessModeValues() []MountAccessMode {
	return []MountAccessMode{
		MountAccessModeRw,
		MountAccessModeRo,
	}
}

type MountType string

const (
	MountTypeVolume MountType = "volume"
	MountTypeBind   MountType = "bind"
	MountTypeTmpfs  MountType = "tmpfs"
)

func (e *MountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MountType(s)
	case string:
		*e = MountType(s)
	default:
		return fmt.Errorf("unsupported scan type for MountType: %T", src)
	}
	return nil
}

type NullMountType struct {
	MountType MountType `json:"mount_type"`
	Valid     bool      `json:"valid"` // Valid is true if MountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMountType) Scan(value interface{}) error {
	if value == nil {
		ns.MountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MountType), nil
}

func AllMountTypeValues() []MountType {
	return []MountType{
		MountTypeVolume,
		MountTypeBind,
		MountTypeTmpfs,
	}
}

type RuleAction string

const (
	RuleActionInclude RuleAction = "include"
	RuleActionExclude RuleAction = "exclude"
)

func (e *RuleAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleAction(s)
	case string:
		*e = RuleAction(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleAction: %T", src)
	}
	return nil
}

type NullRuleAction struct {
	RuleAction RuleAction `json:"rule_action"`
	Valid      bool       `json:"valid"` // Valid is true if RuleAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleAction) Scan(value interface{}) error {
	if value == nil {
		ns.RuleAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleAction), nil
}

func AllRuleActionValues() []RuleAction {
	return []RuleAction{
		RuleActionInclude,
		RuleActionExclude,
	}
}

type RuleEvaluationStatus string

const (
	RuleEvaluationStatusPending RuleEvaluationStatus = "pending"
	RuleEvaluationStatusSuccess RuleEvaluationStatus = "success"
	RuleEvaluationStatusError   RuleEvaluationStatus = "error"
	RuleEvaluationStatusSkipped RuleEvaluationStatus = "skipped"
)

func (e *RuleEvaluationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleEvaluationStatus(s)
	case string:
		*e = RuleEvaluationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleEvaluationStatus: %T", src)
	}
	return nil
}

type NullRuleEvaluationStatus struct {
	RuleEvaluationStatus RuleEvaluationStatus `json:"rule_evaluation_status"`
	Valid                bool                 `json:"valid"` // Valid is true if RuleEvaluationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleEvaluationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RuleEvaluationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleEvaluationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleEvaluationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleEvaluationStatus), nil
}

func AllRuleEvaluationStatusValues() []RuleEvaluationStatus {
	return []RuleEvaluationStatus{
		RuleEvaluationStatusPending,
		RuleEvaluationStatusSuccess,
		RuleEvaluationStatusError,
		RuleEvaluationStatusSkipped,
	}
}

type RuleOperator string

const (
	RuleOperatorEquals      RuleOperator = "equals"
	RuleOperatorNotEquals   RuleOperator = "not_equals"
	RuleOperatorRegex       RuleOperator = "regex"
	RuleOperatorNotRegex    RuleOperator = "not_regex"
	RuleOperatorPrefix      RuleOperator = "prefix"
	RuleOperatorSuffix      RuleOperator = "suffix"
	RuleOperatorContains    RuleOperator = "contains"
	RuleOperatorNotContains RuleOperator = "not_contains"
	RuleOperatorGlob        RuleOperator = "glob"
	RuleOperatorIn          RuleOperator = "in"
	RuleOperatorNotIn       RuleOperator = "not_in"
)

func (e *RuleOperator) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleOperator(s)
	case string:
		*e = RuleOperator(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleOperator: %T", src)
	}
	return nil
}

type NullRuleOperator struct {
	RuleOperator RuleOperator `json:"rule_operator"`
	Valid        bool         `json:"valid"` // Valid is true if RuleOperator is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleOperator) Scan(value interface{}) error {
	if value == nil {
		ns.RuleOperator, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleOperator.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleOperator) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleOperator), nil
}

func AllRuleOperatorValues() []RuleOperator {
	return []RuleOperator{
		RuleOperatorEquals,
		RuleOperatorNotEquals,
		RuleOperatorRegex,
		RuleOperatorNotRegex,
		RuleOperatorPrefix,
		RuleOperatorSuffix,
		RuleOperatorContains,
		RuleOperatorNotContains,
		RuleOperatorGlob,
		RuleOperatorIn,
		RuleOperatorNotIn,
	}
}

type ActiveScans struct {
	ScanID                 string             `json:"scan_id"`
	VolumeID               pgtype.Text        `json:"volume_id"`
	Status                 string             `json:"status"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage           pgtype.Text        `json:"error_message"`
	OverallProgressPercent interface{}        `json:"overall_progress_percent"`
	TotalPhases            int64              `json:"total_phases"`
	CompletedPhases        int64              `json:"completed_phases"`
	RunningPhases          int64              `json:"running_phases"`
	FailedPhases           int64              `json:"failed_phases"`
	DurationSeconds        pgtype.Numeric     `json:"duration_seconds"`
	SecondsSinceUpdate     pgtype.Numeric     `json:"seconds_since_update"`
}

type AlertDeliveries struct {
	ID            int64              `json:"id"`
	AlertID       int64              `json:"alert_id"`
	DestinationID int64              `json:"destination_id"`
	Status        string             `json:"status"`
	AttemptCount  pgtype.Int4        `json:"attempt_count"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	ResponseData  []byte             `json:"response_data"`
	CreatedAt     time.Time          `json:"created_at"`
}

type AlertDestinations struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	Configuration []byte             `json:"configuration"`
	IsEnabled     pgtype.Bool        `json:"is_enabled"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type AlertRoutes struct {
	ID             int64       `json:"id"`
	RuleID         int64       `json:"rule_id"`
	DestinationID  int64       `json:"destination_id"`
	SeverityFilter pgtype.Text `json:"severity_filter"`
	CreatedAt      time.Time   `json:"created_at"`
}

type AlertRules struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	RuleType          string             `json:"rule_type"`
	MetricName        string             `json:"metric_name"`
	ConditionOperator string             `json:"condition_operator"`
	ThresholdValue    pgtype.Numeric     `json:"threshold_value"`
	TimeWindowMinutes pgtype.Int4        `json:"time_window_minutes"`
	MinOccurrences    pgtype.Int4        `json:"min_occurrences"`
	IsEnabled         pgtype.Bool        `json:"is_enabled"`
	Severity          string             `json:"severity"`
	CooldownMinutes   pgtype.Int4        `json:"cooldown_minutes"`
	LastTriggeredAt   pgtype.Timestamptz `json:"last_triggered_at"`
	TriggerCount      pgtype.Int4        `json:"trigger_count"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	OrganizationID    pgtype.Int8        `json:"organization_id"`
}

type Alerts struct {
	ID          int64              `json:"id"`
	RuleID      int64              `json:"rule_id"`
	VolumeID    pgtype.Text        `json:"volume_id"`
	Severity    string             `json:"severity"`
	Title       string             `json:"title"`
	Message     string             `json:"message"`
	ContextData []byte             `json:"context_data"`
	IsResolved  pgtype.Bool        `json:"is_resolved"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type AuditLogs struct {
	ID             int64       `json:"id"`
	OrganizationID int64       `json:"organization_id"`
	UserID         pgtype.Int8 `json:"user_id"`
	Action         string      `json:"action"`
	ResourceType   pgtype.Text `json:"resource_type"`
	ResourceID     pgtype.Text `json:"resource_id"`
	IpAddress      pgtype.Text `json:"ip_address"`
	UserAgent      pgtype.Text `json:"user_agent"`
	Status         string      `json:"status"`
	Details        []byte      `json:"details"`
	CreatedAt      time.Time   `json:"created_at"`
}

type DailyStats struct {
	ID              int64          `json:"id"`
	VolumeID        string         `json:"volume_id"`
	Date            pgtype.Date    `json:"date"`
	TotalSizeBytes  pgtype.Int8    `json:"total_size_bytes"`
	SizeChangeBytes pgtype.Int8    `json:"size_change_bytes"`
	GrowthPercent   pgtype.Numeric `json:"growth_percent"`
	TotalFiles      pgtype.Int8    `json:"total_files"`
	NewFiles        pgtype.Int8    `json:"new_files"`
	DeletedFiles    pgtype.Int8    `json:"deleted_files"`
	ModifiedFiles   pgtype.Int8    `json:"modified_files"`
	MediaFiles      pgtype.Int8    `json:"media_files"`
	DocumentFiles   pgtype.Int8    `json:"document_files"`
	CodeFiles       pgtype.Int8    `json:"code_files"`
	ArchiveFiles    pgtype.Int8    `json:"archive_files"`
	OtherFiles      pgtype.Int8    `json:"other_files"`
	ScanDurationMs  pgtype.Int8    `json:"scan_duration_ms"`
	CreatedAt       time.Time      `json:"created_at"`
}

type DockerMountAttachments struct {
	ID                              int64              `json:"id"`
	MountCatalogID                  pgtype.Int8        `json:"mount_catalog_id"`
	ContainerID                     string             `json:"container_id"`
	ContainerName                   pgtype.Text        `json:"container_name"`
	DestinationPath                 string             `json:"destination_path"`
	AccessMode                      string             `json:"access_mode"`
	Propagation                     pgtype.Text        `json:"propagation"`
	ContainerState                  pgtype.Text        `json:"container_state"`
	ContainerImage                  pgtype.Text        `json:"container_image"`
	ContainerLabels                 []byte             `json:"container_labels"`
	ContainerComposeProject         pgtype.Text        `json:"container_compose_project"`
	ContainerComposeService         pgtype.Text        `json:"container_compose_service"`
	ContainerComposeContainerNumber pgtype.Int4        `json:"container_compose_container_number"`
	ContainerComposeConfigHash      pgtype.Text        `json:"container_compose_config_hash"`
	AttachedAt                      pgtype.Timestamptz `json:"attached_at"`
	DetachedAt                      pgtype.Timestamptz `json:"detached_at"`
	IsActive                        bool               `json:"is_active"`
	CreatedAt                       time.Time          `json:"created_at"`
	UpdatedAt                       time.Time          `json:"updated_at"`
}

type DockerMountCatalog struct {
	ID                 int64              `json:"id"`
	MountID            string             `json:"mount_id"`
	MountType          string             `json:"mount_type"`
	VolumeName         pgtype.Text        `json:"volume_name"`
	VolumeDriver       pgtype.Text        `json:"volume_driver"`
	VolumeOptions      []byte             `json:"volume_options"`
	VolumeLabels       []byte             `json:"volume_labels"`
	VolumeScope        pgtype.Text        `json:"volume_scope"`
	SourcePath         string             `json:"source_path"`
	ContainerCount     int32              `json:"container_count"`
	IsOrphaned         bool               `json:"is_orphaned"`
	ComposeProject     pgtype.Text        `json:"compose_project"`
	ComposeServices    []string           `json:"compose_services"`
	ComposeVersion     pgtype.Text        `json:"compose_version"`
	ComposeConfigFiles []string           `json:"compose_config_files"`
	FirstDiscoveredAt  pgtype.Timestamptz `json:"first_discovered_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	DiscoverySource    string             `json:"discovery_source"`
	IsTracked          bool               `json:"is_tracked"`
	TrackingEnabledAt  pgtype.Timestamptz `json:"tracking_enabled_at"`
	TrackingDisabledAt pgtype.Timestamptz `json:"tracking_disabled_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	OrganizationID     pgtype.Int8        `json:"organization_id"`
}

type DockerMountStatistics struct {
	ID                       int64              `json:"id"`
	MountCatalogID           int64              `json:"mount_catalog_id"`
	PeakContainerCount       int32              `json:"peak_container_count"`
	TotalAttachments         int32              `json:"total_attachments"`
	ComposeProjectsCount     int32              `json:"compose_projects_count"`
	ComposeServicesCount     int32              `json:"compose_services_count"`
	DaysSinceCreation        pgtype.Int4        `json:"days_since_creation"`
	DaysSinceLastUse         pgtype.Int4        `json:"days_since_last_use"`
	AttachmentFrequencyScore pgtype.Float4      `json:"attachment_frequency_score"`
	LastKnownSizeBytes       pgtype.Int8        `json:"last_known_size_bytes"`
	LastScannedAt            pgtype.Timestamptz `json:"last_scanned_at"`
	CalculatedAt             pgtype.Timestamptz `json:"calculated_at"`
	CreatedAt                time.Time          `json:"created_at"`
	UpdatedAt                time.Time          `json:"updated_at"`
}

type DockerProjects struct {
	ID               int64              `json:"id"`
	ProjectName      string             `json:"project_name"`
	ComposeFilePath  pgtype.Text        `json:"compose_file_path"`
	ComposeFileHash  pgtype.Text        `json:"compose_file_hash"`
	WorkingDirectory pgtype.Text        `json:"working_directory"`
	Services         []string           `json:"services"`
	Networks         []string           `json:"networks"`
	Volumes          []string           `json:"volumes"`
	ConfigData       []byte             `json:"config_data"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type FileMetadata struct {
	ID                   int64              `json:"id"`
	FileID               int64              `json:"file_id"`
	RawMetadata          []byte             `json:"raw_metadata"`
	ExtractedAt          pgtype.Timestamptz `json:"extracted_at"`
	ExtractorVersion     pgtype.Text        `json:"extractor_version"`
	ExtractionDurationMs pgtype.Int4        `json:"extraction_duration_ms"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
}

type FilePreviews struct {
	ID                   int64              `json:"id"`
	FileID               int64              `json:"file_id"`
	PreviewType          string             `json:"preview_type"`
	FilePath             string             `json:"file_path"`
	FileSize             pgtype.Int8        `json:"file_size"`
	Width                pgtype.Int4        `json:"width"`
	Height               pgtype.Int4        `json:"height"`
	Format               pgtype.Text        `json:"format"`
	Status               string             `json:"status"`
	GeneratedAt          pgtype.Timestamptz `json:"generated_at"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	ProcessingDurationMs pgtype.Int4        `json:"processing_duration_ms"`
	CreatedAt            time.Time          `json:"created_at"`
}

type Files struct {
	ID                     int64              `json:"id"`
	VolumeID               string             `json:"volume_id"`
	FolderID               pgtype.Int8        `json:"folder_id"`
	Path                   string             `json:"path"`
	PathHash               []byte             `json:"path_hash"`
	Name                   string             `json:"name"`
	Extension              pgtype.Text        `json:"extension"`
	Mime                   pgtype.Text        `json:"mime"`
	SizeBytes              int64              `json:"size_bytes"`
	CreatedAt              time.Time          `json:"created_at"`
	ModifiedAt             pgtype.Timestamptz `json:"modified_at"`
	AccessedAt             pgtype.Timestamptz `json:"accessed_at"`
	Mode                   pgtype.Int4        `json:"mode"`
	OwnerUid               pgtype.Int4        `json:"owner_uid"`
	OwnerGid               pgtype.Int4        `json:"owner_gid"`
	ContentHash            pgtype.Text        `json:"content_hash"`
	IsText                 pgtype.Bool        `json:"is_text"`
	IsBinary               pgtype.Bool        `json:"is_binary"`
	MediaKind              pgtype.Text        `json:"media_kind"`
	DurationMs             pgtype.Int8        `json:"duration_ms"`
	BitrateKbps            pgtype.Int4        `json:"bitrate_kbps"`
	Width                  pgtype.Int4        `json:"width"`
	Height                 pgtype.Int4        `json:"height"`
	Fps                    pgtype.Numeric     `json:"fps"`
	ColorPrimaries         pgtype.Text        `json:"color_primaries"`
	TransferCharacteristic pgtype.Text        `json:"transfer_characteristic"`
	HdrFormat              pgtype.Text        `json:"hdr_format"`
	CaptureDatetime        pgtype.Timestamptz `json:"capture_datetime"`
	CameraMake             pgtype.Text        `json:"camera_make"`
	CameraModel            pgtype.Text        `json:"camera_model"`
	LensModel              pgtype.Text        `json:"lens_model"`
	Orientation            pgtype.Int4        `json:"orientation"`
	GpsLatitude            pgtype.Numeric     `json:"gps_latitude"`
	GpsLongitude           pgtype.Numeric     `json:"gps_longitude"`
	SubtitleLanguage       pgtype.Text        `json:"subtitle_language"`
	SubtitleFormat         pgtype.Text        `json:"subtitle_format"`
	CueCount               pgtype.Int4        `json:"cue_count"`
	CoveragePercent        pgtype.Numeric     `json:"coverage_percent"`
	AudioChannels          pgtype.Int4        `json:"audio_channels"`
	AudioCodec             pgtype.Text        `json:"audio_codec"`
	AudioSampleRate        pgtype.Int4        `json:"audio_sample_rate"`
	VideoCodec             pgtype.Text        `json:"video_codec"`
	VideoProfile           pgtype.Text        `json:"video_profile"`
	VideoLevel             pgtype.Text        `json:"video_level"`
	FirstSeenAt            pgtype.Timestamptz `json:"first_seen_at"`
	LastScanAt             pgtype.Timestamptz `json:"last_scan_at"`
	OrganizationID         pgtype.Int8        `json:"organization_id"`
}

type Folders struct {
	ID                 int64              `json:"id"`
	VolumeID           string             `json:"volume_id"`
	ParentID           pgtype.Int8        `json:"parent_id"`
	Path               string             `json:"path"`
	Name               string             `json:"name"`
	PathHash           []byte             `json:"path_hash"`
	SizeBytes          pgtype.Int8        `json:"size_bytes"`
	SizeBytesRecursive pgtype.Int8        `json:"size_bytes_recursive"`
	FileCount          pgtype.Int4        `json:"file_count"`
	FileCountRecursive pgtype.Int4        `json:"file_count_recursive"`
	SubfolderCount     pgtype.Int4        `json:"subfolder_count"`
	MediaFileCount     pgtype.Int4        `json:"media_file_count"`
	HasMediaFiles      pgtype.Bool        `json:"has_media_files"`
	CreatedAt          time.Time          `json:"created_at"`
	ModifiedAt         pgtype.Timestamptz `json:"modified_at"`
	AccessedAt         pgtype.Timestamptz `json:"accessed_at"`
	OrganizationID     pgtype.Int8        `json:"organization_id"`
}

type MountTrackingAssignments struct {
	ID                int64              `json:"id"`
	MountCatalogID    pgtype.Int8        `json:"mount_catalog_id"`
	RuleID            pgtype.Int8        `json:"rule_id"`
	EvaluationID      pgtype.Int8        `json:"evaluation_id"`
	Action            string             `json:"action"`
	IsActive          bool               `json:"is_active"`
	MatchedConditions []byte             `json:"matched_conditions"`
	RulePriority      pgtype.Int4        `json:"rule_priority"`
	RuleName          pgtype.Text        `json:"rule_name"`
	AssignedAt        pgtype.Timestamptz `json:"assigned_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type OrganizationInvitations struct {
	ID             int64            `json:"id"`
	OrganizationID int64            `json:"organization_id"`
	Email          string           `json:"email"`
	Role           string           `json:"role"`
	Token          string           `json:"token"`
	InvitedBy      pgtype.Int8      `json:"invited_by"`
	Status         string           `json:"status"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	AcceptedAt     pgtype.Timestamp `json:"accepted_at"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type Organizations struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	DisplayName  string      `json:"display_name"`
	Description  pgtype.Text `json:"description"`
	Subdomain    pgtype.Text `json:"subdomain"`
	Settings     []byte      `json:"settings"`
	IsActive     pgtype.Bool `json:"is_active"`
	MaxUsers     pgtype.Int4 `json:"max_users"`
	MaxVolumes   pgtype.Int4 `json:"max_volumes"`
	MaxStorageGb pgtype.Int8 `json:"max_storage_gb"`
	PlanType     pgtype.Text `json:"plan_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type PendingInvitations struct {
	ID                int64            `json:"id"`
	OrganizationID    int64            `json:"organization_id"`
	OrganizationName  string           `json:"organization_name"`
	Email             string           `json:"email"`
	Role              string           `json:"role"`
	Token             string           `json:"token"`
	InvitedBy         pgtype.Int8      `json:"invited_by"`
	InvitedByUsername pgtype.Text      `json:"invited_by_username"`
	ExpiresAt         pgtype.Timestamp `json:"expires_at"`
	CreatedAt         time.Time        `json:"created_at"`
}

type Permissions struct {
	ID             int64       `json:"id"`
	Role           string      `json:"role"`
	Resource       string      `json:"resource"`
	Action         string      `json:"action"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

type RecentAuditEvents struct {
	ID             int64       `json:"id"`
	OrganizationID int64       `json:"organization_id"`
	UserID         pgtype.Int8 `json:"user_id"`
	Username       pgtype.Text `json:"username"`
	Email          pgtype.Text `json:"email"`
	Action         string      `json:"action"`
	ResourceType   pgtype.Text `json:"resource_type"`
	ResourceID     pgtype.Text `json:"resource_id"`
	IpAddress      pgtype.Text `json:"ip_address"`
	Status         string      `json:"status"`
	Details        []byte      `json:"details"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Roles struct {
	ID             int64       `json:"id"`
	OrganizationID int64       `json:"organization_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	IsSystem       bool        `json:"is_system"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type SavedSearches struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Query          []byte             `json:"query"`
	Tags           []string           `json:"tags"`
	IsPublic       pgtype.Bool        `json:"is_public"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	LastRunAt      pgtype.Timestamptz `json:"last_run_at"`
	RunCount       pgtype.Int4        `json:"run_count"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
}

// Stores periodic checkpoints during volume scans to enable resume capability after crashes or interruptions. Critical for 1TB+ volumes with multi-hour scan times.
type ScanCheckpoints struct {
	ID       int64  `json:"id"`
	ScanID   string `json:"scan_id"`
	VolumeID string `json:"volume_id"`
	// Type of scan phase being checkpointed: volume_scan (size calculation), filesystem_indexing (file/folder crawl), enrichment (media metadata)
	CheckpointType string      `json:"checkpoint_type"`
	Phase          string      `json:"phase"`
	Progress       float64     `json:"progress"`
	ItemsProcessed int64       `json:"items_processed"`
	BytesProcessed int64       `json:"bytes_processed"`
	ErrorsCount    int64       `json:"errors_count"`
	LastPath       pgtype.Text `json:"last_path"`
	LastDepth      pgtype.Int4 `json:"last_depth"`
	// ID of last processed folder in folders table. Used to resume filesystem indexing from exact position.
	LastFolderID pgtype.Int8 `json:"last_folder_id"`
	// JSON object containing phase-specific data needed to resume. Example: {"method": "diskus", "started_at": "2025-10-05T10:00:00Z"}
	ResumeData []byte    `json:"resume_data"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type ScanErrors struct {
	ID               int64              `json:"id"`
	ScanID           string             `json:"scan_id"`
	PhaseName        pgtype.Text        `json:"phase_name"`
	ErrorType        string             `json:"error_type"`
	ErrorCategory    pgtype.Text        `json:"error_category"`
	Severity         pgtype.Text        `json:"severity"`
	Component        pgtype.Text        `json:"component"`
	Operation        pgtype.Text        `json:"operation"`
	ItemPath         pgtype.Text        `json:"item_path"`
	ItemName         pgtype.Text        `json:"item_name"`
	ItemType         pgtype.Text        `json:"item_type"`
	ItemSize         pgtype.Int8        `json:"item_size"`
	ErrorMessage     string             `json:"error_message"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	StackTrace       pgtype.Text        `json:"stack_trace"`
	TechnicalDetails pgtype.Text        `json:"technical_details"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	Context          pgtype.Text        `json:"context"`
	RetryCount       pgtype.Int4        `json:"retry_count"`
	MaxRetries       pgtype.Int4        `json:"max_retries"`
	RetryAfter       pgtype.Timestamptz `json:"retry_after"`
	CreatedAt        time.Time          `json:"created_at"`
}

type ScanHistory struct {
	ScanID              string             `json:"scan_id"`
	VolumeID            pgtype.Text        `json:"volume_id"`
	Status              string             `json:"status"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	DurationSeconds     pgtype.Numeric     `json:"duration_seconds"`
	CompletedPhases     int64              `json:"completed_phases"`
	FailedPhases        int64              `json:"failed_phases"`
	TotalItemsProcessed int64              `json:"total_items_processed"`
}

type ScanJobs struct {
	ScanID              string             `json:"scan_id"`
	VolumeID            pgtype.Text        `json:"volume_id"`
	Status              string             `json:"status"`
	TotalFiles          pgtype.Int8        `json:"total_files"`
	ScannedFiles        pgtype.Int8        `json:"scanned_files"`
	FailedFiles         pgtype.Int8        `json:"failed_files"`
	TotalBytes          pgtype.Int8        `json:"total_bytes"`
	ScannedBytes        pgtype.Int8        `json:"scanned_bytes"`
	ScanRateFilesPerSec pgtype.Numeric     `json:"scan_rate_files_per_sec"`
	ScanRateMbPerSec    pgtype.Numeric     `json:"scan_rate_mb_per_sec"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	ErrorDetails        []byte             `json:"error_details"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	PausedAt            pgtype.Timestamptz `json:"paused_at"`
	PauseReason         pgtype.Text        `json:"pause_reason"`
	DurationSeconds     pgtype.Int4        `json:"duration_seconds"`
	TriggeredBy         pgtype.Text        `json:"triggered_by"`
	ScanOptions         []byte             `json:"scan_options"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	OrganizationID      pgtype.Int8        `json:"organization_id"`
}

type ScanPerformanceMetrics struct {
	ID          int64              `json:"id"`
	ScanID      string             `json:"scan_id"`
	MetricName  string             `json:"metric_name"`
	MetricValue pgtype.Numeric     `json:"metric_value"`
	MetricUnit  pgtype.Text        `json:"metric_unit"`
	MeasuredAt  pgtype.Timestamptz `json:"measured_at"`
	Phase       pgtype.Text        `json:"phase"`
}

type ScanPhaseSteps struct {
	ID              int64              `json:"id"`
	PhaseID         int64              `json:"phase_id"`
	StepName        string             `json:"step_name"`
	StepOrder       int32              `json:"step_order"`
	Status          string             `json:"status"`
	ProgressPercent pgtype.Int4        `json:"progress_percent"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	DurationMs      pgtype.Int8        `json:"duration_ms"`
	ResultData      []byte             `json:"result_data"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       time.Time          `json:"created_at"`
}

type ScanPhases struct {
	ID                    int64              `json:"id"`
	ScanID                string             `json:"scan_id"`
	PhaseName             string             `json:"phase_name"`
	Status                string             `json:"status"`
	ProgressPercent       pgtype.Int4        `json:"progress_percent"`
	ItemsTotal            pgtype.Int8        `json:"items_total"`
	ItemsProcessed        pgtype.Int8        `json:"items_processed"`
	ItemsFailed           pgtype.Int8        `json:"items_failed"`
	CurrentItem           pgtype.Text        `json:"current_item"`
	StartedAt             pgtype.Timestamptz `json:"started_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	DurationMs            pgtype.Int8        `json:"duration_ms"`
	ThroughputItemsPerSec pgtype.Numeric     `json:"throughput_items_per_sec"`
	MemoryUsageMb         pgtype.Int8        `json:"memory_usage_mb"`
	ErrorMessage          pgtype.Text        `json:"error_message"`
	PauseReason           pgtype.Text        `json:"pause_reason"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	// Current sub-phase or enricher being executed (e.g., ffprobe, exiftool)
	SubPhase pgtype.Text `json:"sub_phase"`
	Progress pgtype.Int4 `json:"progress"`
}

type ScanProgressSummary struct {
	ScanID                string             `json:"scan_id"`
	VolumeID              pgtype.Text        `json:"volume_id"`
	ScanStatus            string             `json:"scan_status"`
	ScanStartedAt         pgtype.Timestamptz `json:"scan_started_at"`
	ScanCompletedAt       pgtype.Timestamptz `json:"scan_completed_at"`
	PhaseName             pgtype.Text        `json:"phase_name"`
	PhaseStatus           pgtype.Text        `json:"phase_status"`
	PhaseStartedAt        pgtype.Timestamptz `json:"phase_started_at"`
	PhaseCompletedAt      pgtype.Timestamptz `json:"phase_completed_at"`
	ItemsProcessed        pgtype.Int8        `json:"items_processed"`
	ItemsTotal            pgtype.Int8        `json:"items_total"`
	ItemsFailed           pgtype.Int8        `json:"items_failed"`
	CurrentItem           pgtype.Text        `json:"current_item"`
	ProgressPercent       pgtype.Int4        `json:"progress_percent"`
	PhaseError            pgtype.Text        `json:"phase_error"`
	PauseReason           pgtype.Text        `json:"pause_reason"`
	ThroughputItemsPerSec pgtype.Numeric     `json:"throughput_items_per_sec"`
	MemoryUsageMb         pgtype.Int8        `json:"memory_usage_mb"`
	PhaseProgressPercent  pgtype.Numeric     `json:"phase_progress_percent"`
	PhaseDurationSeconds  pgtype.Numeric     `json:"phase_duration_seconds"`
}

type SchemaMigrations struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

// Background jobs for statistics computation and analysis
type StatsJobs struct {
	ID int64 `json:"id"`
	// Unique identifier for the job (UUID or generated string)
	JobID string `json:"job_id"`
	// Type of statistics job being executed
	JobType string `json:"job_type"`
	// Volume this job is processing (null for system-wide jobs)
	VolumeID pgtype.Text `json:"volume_id"`
	Status   string      `json:"status"`
	// Job progress percentage (0-100)
	Progress     pgtype.Int4        `json:"progress"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	// Job execution duration in milliseconds
	DurationMs pgtype.Int8 `json:"duration_ms"`
	// Number of records/files processed by this job
	RecordsProcessed pgtype.Int8 `json:"records_processed"`
	OrganizationID   pgtype.Int8 `json:"organization_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type TrackingRuleConditions struct {
	ID              int64              `json:"id"`
	RuleID          pgtype.Int8        `json:"rule_id"`
	FieldName       string             `json:"field_name"`
	Operator        string             `json:"operator"`
	Value           pgtype.Text        `json:"value"`
	Values          []string           `json:"values"`
	IsCaseSensitive bool               `json:"is_case_sensitive"`
	Description     pgtype.Text        `json:"description"`
	MatchCount      int32              `json:"match_count"`
	LastMatchedAt   pgtype.Timestamptz `json:"last_matched_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type TrackingRuleEvaluations struct {
	ID              int64              `json:"id"`
	RuleID          pgtype.Int8        `json:"rule_id"`
	EvaluationType  string             `json:"evaluation_type"`
	TriggeredBy     pgtype.Text        `json:"triggered_by"`
	Status          string             `json:"status"`
	MountsEvaluated int32              `json:"mounts_evaluated"`
	MountsMatched   int32              `json:"mounts_matched"`
	MountsIncluded  int32              `json:"mounts_included"`
	MountsExcluded  int32              `json:"mounts_excluded"`
	ExecutionTimeMs pgtype.Int4        `json:"execution_time_ms"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ErrorDetails    []byte             `json:"error_details"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type TrackingRuleTemplates struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	Category     string             `json:"category"`
	TemplateData []byte             `json:"template_data"`
	UsageCount   int32              `json:"usage_count"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	IsBuiltin    bool               `json:"is_builtin"`
	Tags         []string           `json:"tags"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type TrackingRules struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Action           string             `json:"action"`
	Priority         int32              `json:"priority"`
	IsEnabled        bool               `json:"is_enabled"`
	Conditions       []byte             `json:"conditions"`
	MatchCount       int32              `json:"match_count"`
	LastMatchedAt    pgtype.Timestamptz `json:"last_matched_at"`
	LastEvaluationAt pgtype.Timestamptz `json:"last_evaluation_at"`
	CreatedBy        pgtype.Text        `json:"created_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	OrganizationID   pgtype.Int8        `json:"organization_id"`
}

type UsageSnapshots struct {
	ID               int64          `json:"id"`
	VolumeID         string         `json:"volume_id"`
	SnapshotDate     pgtype.Date    `json:"snapshot_date"`
	TotalSizeBytes   int64          `json:"total_size_bytes"`
	TotalFiles       int64          `json:"total_files"`
	TotalDirectories int64          `json:"total_directories"`
	SizeChangeBytes  pgtype.Int8    `json:"size_change_bytes"`
	FilesChange      pgtype.Int8    `json:"files_change"`
	GrowthRate       pgtype.Numeric `json:"growth_rate"`
	LargestFileSize  pgtype.Int8    `json:"largest_file_size"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Users struct {
	ID             int64            `json:"id"`
	OrganizationID int64            `json:"organization_id"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	PasswordHash   string           `json:"password_hash"`
	Role           string           `json:"role"`
	IsActive       bool             `json:"is_active"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
	LastLoginAt    pgtype.Timestamp `json:"last_login_at"`
}

// Stores directory-level snapshots for fine-grained change detection. Allows identifying specific directories that changed.
type VolumeDirectorySnapshots struct {
	ID          int64              `json:"id"`
	SnapshotID  int64              `json:"snapshot_id"`
	VolumeID    string             `json:"volume_id"`
	DirPath     string             `json:"dir_path"`
	DirMtime    pgtype.Timestamptz `json:"dir_mtime"`
	DirSize     int64              `json:"dir_size"`
	FileCount   int32              `json:"file_count"`
	SubdirCount int32              `json:"subdir_count"`
	// Hash of directory contents (filenames + sizes). Used to detect if directory contents changed.
	ContentHash pgtype.Text `json:"content_hash"`
	CreatedAt   time.Time   `json:"created_at"`
}

type VolumeScanStats struct {
	VolumeID               pgtype.Text `json:"volume_id"`
	TotalScans             int64       `json:"total_scans"`
	SuccessfulScans        int64       `json:"successful_scans"`
	FailedScans            int64       `json:"failed_scans"`
	RunningScans           int64       `json:"running_scans"`
	LastScanStarted        interface{} `json:"last_scan_started"`
	LastScanCompleted      interface{} `json:"last_scan_completed"`
	AvgScanDurationSeconds float64     `json:"avg_scan_duration_seconds"`
}

type VolumeSizes struct {
	ID                    int64              `json:"id"`
	VolumeID              string             `json:"volume_id"`
	TotalSize             int64              `json:"total_size"`
	FileCount             int64              `json:"file_count"`
	DirectoryCount        int64              `json:"directory_count"`
	LargestFileSize       pgtype.Int8        `json:"largest_file_size"`
	SmallestFileSize      pgtype.Int8        `json:"smallest_file_size"`
	AverageFileSize       pgtype.Int8        `json:"average_file_size"`
	MedianFileSize        pgtype.Int8        `json:"median_file_size"`
	TypeDistribution      []byte             `json:"type_distribution"`
	ExtensionDistribution []byte             `json:"extension_distribution"`
	CalculatedAt          pgtype.Timestamptz `json:"calculated_at"`
}

// Stores volume state snapshots for incremental scanning. Enables detecting changes between scans to avoid full rescans of unchanged data.
type VolumeSnapshots struct {
	ID           int64              `json:"id"`
	VolumeID     string             `json:"volume_id"`
	ScanID       string             `json:"scan_id"`
	SnapshotTime pgtype.Timestamptz `json:"snapshot_time"`
	ScanMethod   string             `json:"scan_method"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	FolderCount  int64              `json:"folder_count"`
	RootMtime    pgtype.Timestamptz `json:"root_mtime"`
	// Optional hash of directory tree structure. Can be used for quick change detection without walking the filesystem.
	ContentHash        pgtype.Text `json:"content_hash"`
	ScanDurationMs     pgtype.Int8 `json:"scan_duration_ms"`
	IndexingDurationMs pgtype.Int8 `json:"indexing_duration_ms"`
	CreatedAt          time.Time   `json:"created_at"`
}

type Volumes struct {
	VolumeID       string             `json:"volume_id"`
	DisplayName    pgtype.Text        `json:"display_name"`
	MountPoint     string             `json:"mount_point"`
	ContainerNames []string           `json:"container_names"`
	IsActive       pgtype.Bool        `json:"is_active"`
	TotalSizeBytes pgtype.Int8        `json:"total_size_bytes"`
	UsedSizeBytes  pgtype.Int8        `json:"used_size_bytes"`
	FreeSizeBytes  pgtype.Int8        `json:"free_size_bytes"`
	FilesystemType pgtype.Text        `json:"filesystem_type"`
	ContainerCount pgtype.Int4        `json:"container_count"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
	LastScanAt     pgtype.Timestamptz `json:"last_scan_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	// Docker volume driver (local, nfs, cifs, etc.)
	Driver pgtype.Text `json:"driver"`
	// Docker volume scope (local or global)
	Scope pgtype.Text `json:"scope"`
	// Docker volume labels as JSON object
	Labels []byte `json:"labels"`
	// Driver-specific options (e.g., device path for bind mounts)
	Options []byte `json:"options"`
}
