// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: offsets.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeScanJob = `-- name: CompleteScanJob :one
UPDATE scan_jobs 
SET status = $2, progress = 100, completed_at = $3, result_id = $4, updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
RETURNING id, updated_at
`

type CompleteScanJobParams struct {
	ScanID      string           `json:"scan_id"`
	Status      string           `json:"status"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
	ResultID    pgtype.Int8      `json:"result_id"`
}

type CompleteScanJobRow struct {
	ID        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CompleteScanJob(ctx context.Context, arg CompleteScanJobParams) (CompleteScanJobRow, error) {
	row := q.db.QueryRow(ctx, completeScanJob,
		arg.ScanID,
		arg.Status,
		arg.CompletedAt,
		arg.ResultID,
	)
	var i CompleteScanJobRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const createScanJob = `-- name: CreateScanJob :one


INSERT INTO scan_jobs (scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at, updated_at
`

type CreateScanJobParams struct {
	ScanID            string           `json:"scan_id"`
	VolumeID          string           `json:"volume_id"`
	Status            string           `json:"status"`
	Progress          pgtype.Int4      `json:"progress"`
	Method            string           `json:"method"`
	StartedAt         pgtype.Timestamp `json:"started_at"`
	CompletedAt       pgtype.Timestamp `json:"completed_at"`
	ErrorMessage      pgtype.Text      `json:"error_message"`
	ResultID          pgtype.Int8      `json:"result_id"`
	EstimatedDuration pgtype.Int8      `json:"estimated_duration"`
}

type CreateScanJobRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Consolidated queries for scan jobs and health/diagnostic operations
// This file consolidates queries from scan_jobs.sql and health.sql
// =============================================================================
// SCAN JOB OPERATIONS
// =============================================================================
func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (CreateScanJobRow, error) {
	row := q.db.QueryRow(ctx, createScanJob,
		arg.ScanID,
		arg.VolumeID,
		arg.Status,
		arg.Progress,
		arg.Method,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ResultID,
		arg.EstimatedDuration,
	)
	var i CreateScanJobRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteOldScanJobs = `-- name: DeleteOldScanJobs :exec
DELETE FROM scan_jobs 
WHERE created_at < $1 AND status IN ('completed', 'failed')
`

func (q *Queries) DeleteOldScanJobs(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldScanJobs, createdAt)
	return err
}

const failScanJob = `-- name: FailScanJob :one
UPDATE scan_jobs 
SET status = 'failed', error_message = $2, completed_at = $3, updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
RETURNING id, updated_at
`

type FailScanJobParams struct {
	ScanID       string           `json:"scan_id"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

type FailScanJobRow struct {
	ID        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) (FailScanJobRow, error) {
	row := q.db.QueryRow(ctx, failScanJob, arg.ScanID, arg.ErrorMessage, arg.CompletedAt)
	var i FailScanJobRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const getActiveScanJobs = `-- name: GetActiveScanJobs :many
SELECT id, scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration, created_at, updated_at
FROM scan_jobs 
WHERE status IN ('queued', 'running')
ORDER BY created_at ASC
`

func (q *Queries) GetActiveScanJobs(ctx context.Context) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getActiveScanJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.Progress,
			&i.Method,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.ResultID,
			&i.EstimatedDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestScanJobByVolumeID = `-- name: GetLatestScanJobByVolumeID :one
SELECT id, scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration, created_at, updated_at
FROM scan_jobs 
WHERE volume_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestScanJobByVolumeID(ctx context.Context, volumeID string) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, getLatestScanJobByVolumeID, volumeID)
	var i ScanJobs
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.Progress,
		&i.Method,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ResultID,
		&i.EstimatedDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentScanJobs = `-- name: GetRecentScanJobs :many
SELECT id, scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration, created_at, updated_at
FROM scan_jobs
WHERE created_at >= $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentScanJobsParams struct {
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetRecentScanJobs(ctx context.Context, arg GetRecentScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getRecentScanJobs, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.Progress,
			&i.Method,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.ResultID,
			&i.EstimatedDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanJobByID = `-- name: GetScanJobByID :one
SELECT id, scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration, created_at, updated_at
FROM scan_jobs 
WHERE id = $1
`

func (q *Queries) GetScanJobByID(ctx context.Context, id int64) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, getScanJobByID, id)
	var i ScanJobs
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.Progress,
		&i.Method,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ResultID,
		&i.EstimatedDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanJobByScanID = `-- name: GetScanJobByScanID :one
SELECT id, scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration, created_at, updated_at
FROM scan_jobs 
WHERE scan_id = $1
`

func (q *Queries) GetScanJobByScanID(ctx context.Context, scanID string) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, getScanJobByScanID, scanID)
	var i ScanJobs
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.Progress,
		&i.Method,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.ResultID,
		&i.EstimatedDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanJobStats = `-- name: GetScanJobStats :one
SELECT 
    COUNT(*) as total_jobs,
    COALESCE(COUNT(*) FILTER (WHERE status = 'completed'), 0) as completed_jobs,
    COALESCE(COUNT(*) FILTER (WHERE status = 'failed'), 0) as failed_jobs,
    COALESCE(COUNT(*) FILTER (WHERE status IN ('queued', 'running')), 0) as active_jobs,
    AVG(EXTRACT(EPOCH FROM (completed_at - started_at))) as avg_duration_seconds
FROM scan_jobs
`

type GetScanJobStatsRow struct {
	TotalJobs          int64       `json:"total_jobs"`
	CompletedJobs      interface{} `json:"completed_jobs"`
	FailedJobs         interface{} `json:"failed_jobs"`
	ActiveJobs         interface{} `json:"active_jobs"`
	AvgDurationSeconds float64     `json:"avg_duration_seconds"`
}

func (q *Queries) GetScanJobStats(ctx context.Context) (GetScanJobStatsRow, error) {
	row := q.db.QueryRow(ctx, getScanJobStats)
	var i GetScanJobStatsRow
	err := row.Scan(
		&i.TotalJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
		&i.ActiveJobs,
		&i.AvgDurationSeconds,
	)
	return i, err
}

const getTotalMetricsCount = `-- name: GetTotalMetricsCount :one
SELECT COUNT(*) FROM volume_metrics
`

func (q *Queries) GetTotalMetricsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalMetricsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalScanJobCount = `-- name: GetTotalScanJobCount :one
SELECT COUNT(*) FROM scan_jobs
`

func (q *Queries) GetTotalScanJobCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalScanJobCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalVolumeCount = `-- name: GetTotalVolumeCount :one
SELECT COUNT(*) FROM volumes
`

func (q *Queries) GetTotalVolumeCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVolumeCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const healthCheck = `-- name: HealthCheck :one

SELECT 1 as status
`

// =============================================================================
// HEALTH AND DIAGNOSTIC OPERATIONS
// =============================================================================
func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var status int32
	err := row.Scan(&status)
	return status, err
}

const listScanJobs = `-- name: ListScanJobs :many
SELECT id, scan_id, volume_id, status, progress, method, started_at, completed_at, error_message, result_id, estimated_duration, created_at, updated_at
FROM scan_jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListScanJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.Progress,
			&i.Method,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.ResultID,
			&i.EstimatedDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startScanJob = `-- name: StartScanJob :one
UPDATE scan_jobs 
SET status = 'running', started_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
RETURNING id, updated_at
`

type StartScanJobParams struct {
	ScanID    string           `json:"scan_id"`
	StartedAt pgtype.Timestamp `json:"started_at"`
}

type StartScanJobRow struct {
	ID        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) StartScanJob(ctx context.Context, arg StartScanJobParams) (StartScanJobRow, error) {
	row := q.db.QueryRow(ctx, startScanJob, arg.ScanID, arg.StartedAt)
	var i StartScanJobRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs 
SET progress = $2, updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type UpdateScanJobProgressParams struct {
	ScanID   string      `json:"scan_id"`
	Progress pgtype.Int4 `json:"progress"`
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateScanJobProgress, arg.ScanID, arg.Progress)
	return err
}

const updateScanJobStatus = `-- name: UpdateScanJobStatus :one
UPDATE scan_jobs 
SET status = $2, progress = $3, error_message = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING updated_at
`

type UpdateScanJobStatusParams struct {
	ID           int64       `json:"id"`
	Status       string      `json:"status"`
	Progress     pgtype.Int4 `json:"progress"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateScanJobStatus,
		arg.ID,
		arg.Status,
		arg.Progress,
		arg.ErrorMessage,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const updateScanJobStatusAndProgress = `-- name: UpdateScanJobStatusAndProgress :one
UPDATE scan_jobs 
SET status = $2, progress = $3, updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
RETURNING id, updated_at
`

type UpdateScanJobStatusAndProgressParams struct {
	ScanID   string      `json:"scan_id"`
	Status   string      `json:"status"`
	Progress pgtype.Int4 `json:"progress"`
}

type UpdateScanJobStatusAndProgressRow struct {
	ID        int64     `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateScanJobStatusAndProgress(ctx context.Context, arg UpdateScanJobStatusAndProgressParams) (UpdateScanJobStatusAndProgressRow, error) {
	row := q.db.QueryRow(ctx, updateScanJobStatusAndProgress, arg.ScanID, arg.Status, arg.Progress)
	var i UpdateScanJobStatusAndProgressRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
