// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingInvitations = `-- name: CountPendingInvitations :one
SELECT COUNT(*) FROM organization_invitations
WHERE organization_id = $1 AND status = 'pending' AND expires_at > NOW()
`

func (q *Queries) CountPendingInvitations(ctx context.Context, organizationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitations, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO organization_invitations (
    organization_id, email, role, token, invited_by, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at, updated_at
`

type CreateInvitationParams struct {
	OrganizationID int64            `json:"organization_id"`
	Email          string           `json:"email"`
	Role           string           `json:"role"`
	Token          string           `json:"token"`
	InvitedBy      pgtype.Int8      `json:"invited_by"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
}

// Organization invitations queries for VolumeViz
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitations, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvitations
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM organization_invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const expireOldInvitations = `-- name: ExpireOldInvitations :exec
UPDATE organization_invitations SET
    status = 'expired',
    updated_at = NOW()
WHERE status = 'pending' AND expires_at < NOW()
`

func (q *Queries) ExpireOldInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldInvitations)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, organization_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM organization_invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id int64) (OrganizationInvitations, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i OrganizationInvitations
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, organization_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM organization_invitations
WHERE token = $1 AND status = 'pending' AND expires_at > NOW()
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (OrganizationInvitations, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i OrganizationInvitations
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitationsView = `-- name: GetPendingInvitationsView :many
SELECT id, organization_id, organization_name, email, role, token, invited_by, invited_by_username, expires_at, created_at FROM pending_invitations
WHERE organization_id = $1
`

func (q *Queries) GetPendingInvitationsView(ctx context.Context, organizationID int64) ([]PendingInvitations, error) {
	rows, err := q.db.Query(ctx, getPendingInvitationsView, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingInvitations{}
	for rows.Next() {
		var i PendingInvitations
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.InvitedByUsername,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsByOrg = `-- name: ListInvitationsByOrg :many
SELECT id, organization_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM organization_invitations
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvitationsByOrgParams struct {
	OrganizationID int64 `json:"organization_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

func (q *Queries) ListInvitationsByOrg(ctx context.Context, arg ListInvitationsByOrgParams) ([]OrganizationInvitations, error) {
	rows, err := q.db.Query(ctx, listInvitationsByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitations{}
	for rows.Next() {
		var i OrganizationInvitations
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByOrg = `-- name: ListPendingInvitationsByOrg :many
SELECT id, organization_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at, updated_at FROM organization_invitations
WHERE organization_id = $1 AND status = 'pending' AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByOrg(ctx context.Context, organizationID int64) ([]OrganizationInvitations, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitations{}
	for rows.Next() {
		var i OrganizationInvitations
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE organization_invitations SET
    status = 'revoked',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeInvitation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE organization_invitations SET
    status = $2,
    accepted_at = CASE WHEN $2 = 'accepted' THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, email, role, token, invited_by, status, expires_at, accepted_at, created_at, updated_at
`

type UpdateInvitationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (OrganizationInvitations, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i OrganizationInvitations
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
