// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: previews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupStalePreviews = `-- name: CleanupStalePreviews :exec
DELETE FROM file_previews
WHERE status = 'failed'
AND generated_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) CleanupStalePreviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupStalePreviews)
	return err
}

const countPreviewsByStatus = `-- name: CountPreviewsByStatus :one
SELECT COUNT(*) FROM file_previews WHERE status = $1
`

func (q *Queries) CountPreviewsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countPreviewsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPreview = `-- name: CreatePreview :one

INSERT INTO file_previews (
    file_id, preview_type, file_path, file_size,
    width, height, format, status, generated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at
`

type CreatePreviewParams struct {
	FileID      int64              `json:"file_id"`
	PreviewType string             `json:"preview_type"`
	FilePath    string             `json:"file_path"`
	FileSize    pgtype.Int8        `json:"file_size"`
	Width       pgtype.Int4        `json:"width"`
	Height      pgtype.Int4        `json:"height"`
	Format      pgtype.Text        `json:"format"`
	Status      string             `json:"status"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

// Preview management queries for PostgreSQL
func (q *Queries) CreatePreview(ctx context.Context, arg CreatePreviewParams) (FilePreviews, error) {
	row := q.db.QueryRow(ctx, createPreview,
		arg.FileID,
		arg.PreviewType,
		arg.FilePath,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.Format,
		arg.Status,
		arg.GeneratedAt,
	)
	var i FilePreviews
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.PreviewType,
		&i.FilePath,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.Status,
		&i.GeneratedAt,
		&i.ErrorMessage,
		&i.ProcessingDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const deletePreview = `-- name: DeletePreview :exec
DELETE FROM file_previews WHERE id = $1
`

func (q *Queries) DeletePreview(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePreview, id)
	return err
}

const deletePreviewsByFileID = `-- name: DeletePreviewsByFileID :exec
DELETE FROM file_previews WHERE file_id = $1
`

func (q *Queries) DeletePreviewsByFileID(ctx context.Context, fileID int64) error {
	_, err := q.db.Exec(ctx, deletePreviewsByFileID, fileID)
	return err
}

const getPreview = `-- name: GetPreview :one
SELECT id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at FROM file_previews WHERE id = $1
`

func (q *Queries) GetPreview(ctx context.Context, id int64) (FilePreviews, error) {
	row := q.db.QueryRow(ctx, getPreview, id)
	var i FilePreviews
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.PreviewType,
		&i.FilePath,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.Status,
		&i.GeneratedAt,
		&i.ErrorMessage,
		&i.ProcessingDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviewByFileID = `-- name: GetPreviewByFileID :one
SELECT id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at FROM file_previews WHERE file_id = $1 AND preview_type = $2
`

type GetPreviewByFileIDParams struct {
	FileID      int64  `json:"file_id"`
	PreviewType string `json:"preview_type"`
}

func (q *Queries) GetPreviewByFileID(ctx context.Context, arg GetPreviewByFileIDParams) (FilePreviews, error) {
	row := q.db.QueryRow(ctx, getPreviewByFileID, arg.FileID, arg.PreviewType)
	var i FilePreviews
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.PreviewType,
		&i.FilePath,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.Status,
		&i.GeneratedAt,
		&i.ErrorMessage,
		&i.ProcessingDurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviewStats = `-- name: GetPreviewStats :one
SELECT 
    COUNT(*) as total_previews,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_previews,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_previews,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_previews,
    COALESCE(SUM(file_size), 0) as total_size
FROM file_previews
`

type GetPreviewStatsRow struct {
	TotalPreviews     int64       `json:"total_previews"`
	CompletedPreviews int64       `json:"completed_previews"`
	FailedPreviews    int64       `json:"failed_previews"`
	PendingPreviews   int64       `json:"pending_previews"`
	TotalSize         interface{} `json:"total_size"`
}

func (q *Queries) GetPreviewStats(ctx context.Context) (GetPreviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getPreviewStats)
	var i GetPreviewStatsRow
	err := row.Scan(
		&i.TotalPreviews,
		&i.CompletedPreviews,
		&i.FailedPreviews,
		&i.PendingPreviews,
		&i.TotalSize,
	)
	return i, err
}

const getStaleFailedPreviews = `-- name: GetStaleFailedPreviews :many
SELECT id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at FROM file_previews
WHERE status = 'failed'
AND generated_at < NOW() - INTERVAL '30 days'
ORDER BY generated_at ASC NULLS LAST
LIMIT $1
`

func (q *Queries) GetStaleFailedPreviews(ctx context.Context, limit int32) ([]FilePreviews, error) {
	rows, err := q.db.Query(ctx, getStaleFailedPreviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilePreviews{}
	for rows.Next() {
		var i FilePreviews
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.PreviewType,
			&i.FilePath,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Format,
			&i.Status,
			&i.GeneratedAt,
			&i.ErrorMessage,
			&i.ProcessingDurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviews = `-- name: ListPreviews :many
SELECT id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at FROM file_previews
WHERE file_id = ANY($1::bigint[])
ORDER BY generated_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListPreviewsParams struct {
	Column1 []int64 `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) ListPreviews(ctx context.Context, arg ListPreviewsParams) ([]FilePreviews, error) {
	rows, err := q.db.Query(ctx, listPreviews, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilePreviews{}
	for rows.Next() {
		var i FilePreviews
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.PreviewType,
			&i.FilePath,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Format,
			&i.Status,
			&i.GeneratedAt,
			&i.ErrorMessage,
			&i.ProcessingDurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewsByStatus = `-- name: ListPreviewsByStatus :many
SELECT id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at FROM file_previews
WHERE status = $1
ORDER BY generated_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListPreviewsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPreviewsByStatus(ctx context.Context, arg ListPreviewsByStatusParams) ([]FilePreviews, error) {
	rows, err := q.db.Query(ctx, listPreviewsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilePreviews{}
	for rows.Next() {
		var i FilePreviews
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.PreviewType,
			&i.FilePath,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Format,
			&i.Status,
			&i.GeneratedAt,
			&i.ErrorMessage,
			&i.ProcessingDurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePreview = `-- name: UpdatePreview :one
UPDATE file_previews
SET 
    file_path = $2,
    file_size = $3,
    width = $4,
    height = $5,
    format = $6,
    status = $7,
    generated_at = $8
WHERE id = $1
RETURNING id, file_id, preview_type, file_path, file_size, width, height, format, status, generated_at, error_message, processing_duration_ms, created_at
`

type UpdatePreviewParams struct {
	ID          int64              `json:"id"`
	FilePath    string             `json:"file_path"`
	FileSize    pgtype.Int8        `json:"file_size"`
	Width       pgtype.Int4        `json:"width"`
	Height      pgtype.Int4        `json:"height"`
	Format      pgtype.Text        `json:"format"`
	Status      string             `json:"status"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

func (q *Queries) UpdatePreview(ctx context.Context, arg UpdatePreviewParams) (FilePreviews, error) {
	row := q.db.QueryRow(ctx, updatePreview,
		arg.ID,
		arg.FilePath,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.Format,
		arg.Status,
		arg.GeneratedAt,
	)
	var i FilePreviews
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.PreviewType,
		&i.FilePath,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Format,
		&i.Status,
		&i.GeneratedAt,
		&i.ErrorMessage,
		&i.ProcessingDurationMs,
		&i.CreatedAt,
	)
	return i, err
}
