// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelScanJob = `-- name: CancelScanJob :exec
UPDATE scan_jobs
SET 
    status = 'cancelled',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

func (q *Queries) CancelScanJob(ctx context.Context, scanID string) error {
	_, err := q.db.Exec(ctx, cancelScanJob, scanID)
	return err
}

const claimNextScanJob = `-- name: ClaimNextScanJob :one
UPDATE scan_jobs
SET
    status = 'running',
    started_at = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = (
    SELECT scan_id
    FROM scan_jobs
    WHERE status = 'pending'
    ORDER BY started_at ASC NULLS FIRST, scan_id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id
`

func (q *Queries) ClaimNextScanJob(ctx context.Context, startedAt pgtype.Timestamptz) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, claimNextScanJob, startedAt)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const completeScanJob = `-- name: CompleteScanJob :exec
UPDATE scan_jobs
SET 
    status = 'completed',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

func (q *Queries) CompleteScanJob(ctx context.Context, scanID string) error {
	_, err := q.db.Exec(ctx, completeScanJob, scanID)
	return err
}

const countScanJobsByStatus = `-- name: CountScanJobsByStatus :one
SELECT COUNT(*) FROM scan_jobs WHERE status = $1
`

func (q *Queries) CountScanJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanJob = `-- name: CreateScanJob :one

INSERT INTO scan_jobs (
    scan_id, volume_id, status, started_at, organization_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id
`

type CreateScanJobParams struct {
	ScanID         string             `json:"scan_id"`
	VolumeID       pgtype.Text        `json:"volume_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
}

// Scan job management queries for PostgreSQL
func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, createScanJob,
		arg.ScanID,
		arg.VolumeID,
		arg.Status,
		arg.StartedAt,
		arg.OrganizationID,
	)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const deleteOldScanJobs = `-- name: DeleteOldScanJobs :exec
DELETE FROM scan_jobs
WHERE completed_at < $1
AND status IN ('completed', 'failed', 'cancelled')
`

func (q *Queries) DeleteOldScanJobs(ctx context.Context, completedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldScanJobs, completedAt)
	return err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs
SET 
    status = 'failed',
    error_message = $2,
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type FailScanJobParams struct {
	ScanID       string      `json:"scan_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.db.Exec(ctx, failScanJob, arg.ScanID, arg.ErrorMessage)
	return err
}

const getActiveScanByID = `-- name: GetActiveScanByID :one
SELECT scan_id, volume_id, status, started_at, updated_at, completed_at, error_message, overall_progress_percent, total_phases, completed_phases, running_phases, failed_phases, duration_seconds, seconds_since_update FROM active_scans
WHERE scan_id = $1
`

func (q *Queries) GetActiveScanByID(ctx context.Context, scanID string) (ActiveScans, error) {
	row := q.db.QueryRow(ctx, getActiveScanByID, scanID)
	var i ActiveScans
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.OverallProgressPercent,
		&i.TotalPhases,
		&i.CompletedPhases,
		&i.RunningPhases,
		&i.FailedPhases,
		&i.DurationSeconds,
		&i.SecondsSinceUpdate,
	)
	return i, err
}

const getActiveScanJobs = `-- name: GetActiveScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status IN ('pending', 'running')
ORDER BY started_at ASC
`

func (q *Queries) GetActiveScanJobs(ctx context.Context) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getActiveScanJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveScanJobsByOrganization = `-- name: GetActiveScanJobsByOrganization :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status IN ('pending', 'running') AND organization_id = $1
ORDER BY started_at ASC
`

func (q *Queries) GetActiveScanJobsByOrganization(ctx context.Context, organizationID pgtype.Int8) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getActiveScanJobsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveScans = `-- name: GetActiveScans :many

SELECT scan_id, volume_id, status, started_at, updated_at, completed_at, error_message, overall_progress_percent, total_phases, completed_phases, running_phases, failed_phases, duration_seconds, seconds_since_update FROM active_scans
ORDER BY started_at DESC
`

// ============================================================================
// Database View Queries
// ============================================================================
// These queries access the monitoring views created in migration 000008
func (q *Queries) GetActiveScans(ctx context.Context) ([]ActiveScans, error) {
	rows, err := q.db.Query(ctx, getActiveScans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveScans{}
	for rows.Next() {
		var i ActiveScans
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.OverallProgressPercent,
			&i.TotalPhases,
			&i.CompletedPhases,
			&i.RunningPhases,
			&i.FailedPhases,
			&i.DurationSeconds,
			&i.SecondsSinceUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveScansByOrganization = `-- name: GetActiveScansByOrganization :many
SELECT a.scan_id, a.volume_id, a.status, a.started_at, a.updated_at, a.completed_at, a.error_message, a.overall_progress_percent, a.total_phases, a.completed_phases, a.running_phases, a.failed_phases, a.duration_seconds, a.seconds_since_update FROM active_scans a
JOIN volumes v ON a.volume_id = v.id
WHERE v.organization_id = $1
ORDER BY a.started_at DESC
`

func (q *Queries) GetActiveScansByOrganization(ctx context.Context, organizationID pgtype.Int8) ([]ActiveScans, error) {
	rows, err := q.db.Query(ctx, getActiveScansByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveScans{}
	for rows.Next() {
		var i ActiveScans
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.OverallProgressPercent,
			&i.TotalPhases,
			&i.CompletedPhases,
			&i.RunningPhases,
			&i.FailedPhases,
			&i.DurationSeconds,
			&i.SecondsSinceUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedScanJobs = `-- name: GetCompletedScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status = 'completed'
AND completed_at >= $1
ORDER BY completed_at DESC
LIMIT $2
`

type GetCompletedScanJobsParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetCompletedScanJobs(ctx context.Context, arg GetCompletedScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getCompletedScanJobs, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanHistory = `-- name: GetScanHistory :many
SELECT scan_id, volume_id, status, started_at, completed_at, duration_seconds, completed_phases, failed_phases, total_items_processed FROM scan_history
LIMIT $1 OFFSET $2
`

type GetScanHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetScanHistory(ctx context.Context, arg GetScanHistoryParams) ([]ScanHistory, error) {
	rows, err := q.db.Query(ctx, getScanHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanHistory{}
	for rows.Next() {
		var i ScanHistory
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationSeconds,
			&i.CompletedPhases,
			&i.FailedPhases,
			&i.TotalItemsProcessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanHistoryByOrganization = `-- name: GetScanHistoryByOrganization :many
SELECT s.scan_id, s.volume_id, s.status, s.started_at, s.completed_at, s.duration_seconds, s.completed_phases, s.failed_phases, s.total_items_processed FROM scan_history s
JOIN volumes v ON s.volume_id = v.id
WHERE v.organization_id = $1
ORDER BY s.completed_at DESC
LIMIT $2 OFFSET $3
`

type GetScanHistoryByOrganizationParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) GetScanHistoryByOrganization(ctx context.Context, arg GetScanHistoryByOrganizationParams) ([]ScanHistory, error) {
	rows, err := q.db.Query(ctx, getScanHistoryByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanHistory{}
	for rows.Next() {
		var i ScanHistory
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationSeconds,
			&i.CompletedPhases,
			&i.FailedPhases,
			&i.TotalItemsProcessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanHistoryByVolume = `-- name: GetScanHistoryByVolume :many
SELECT scan_id, volume_id, status, started_at, completed_at, duration_seconds, completed_phases, failed_phases, total_items_processed FROM scan_history
WHERE volume_id = $1
ORDER BY completed_at DESC
LIMIT $2 OFFSET $3
`

type GetScanHistoryByVolumeParams struct {
	VolumeID pgtype.Text `json:"volume_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetScanHistoryByVolume(ctx context.Context, arg GetScanHistoryByVolumeParams) ([]ScanHistory, error) {
	rows, err := q.db.Query(ctx, getScanHistoryByVolume, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanHistory{}
	for rows.Next() {
		var i ScanHistory
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationSeconds,
			&i.CompletedPhases,
			&i.FailedPhases,
			&i.TotalItemsProcessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanJobByScanID = `-- name: GetScanJobByScanID :one
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs WHERE scan_id = $1
`

func (q *Queries) GetScanJobByScanID(ctx context.Context, scanID string) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, getScanJobByScanID, scanID)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getScanProgressSummary = `-- name: GetScanProgressSummary :many
SELECT scan_id, volume_id, scan_status, scan_started_at, scan_completed_at, phase_name, phase_status, phase_started_at, phase_completed_at, items_processed, items_total, items_failed, current_item, progress_percent, phase_error, pause_reason, throughput_items_per_sec, memory_usage_mb, phase_progress_percent, phase_duration_seconds FROM scan_progress_summary
WHERE scan_id = $1
ORDER BY phase_started_at ASC
`

func (q *Queries) GetScanProgressSummary(ctx context.Context, scanID string) ([]ScanProgressSummary, error) {
	rows, err := q.db.Query(ctx, getScanProgressSummary, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanProgressSummary{}
	for rows.Next() {
		var i ScanProgressSummary
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.ScanStatus,
			&i.ScanStartedAt,
			&i.ScanCompletedAt,
			&i.PhaseName,
			&i.PhaseStatus,
			&i.PhaseStartedAt,
			&i.PhaseCompletedAt,
			&i.ItemsProcessed,
			&i.ItemsTotal,
			&i.ItemsFailed,
			&i.CurrentItem,
			&i.ProgressPercent,
			&i.PhaseError,
			&i.PauseReason,
			&i.ThroughputItemsPerSec,
			&i.MemoryUsageMb,
			&i.PhaseProgressPercent,
			&i.PhaseDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanProgressSummaryByVolume = `-- name: GetScanProgressSummaryByVolume :many
SELECT s.scan_id, s.volume_id, s.scan_status, s.scan_started_at, s.scan_completed_at, s.phase_name, s.phase_status, s.phase_started_at, s.phase_completed_at, s.items_processed, s.items_total, s.items_failed, s.current_item, s.progress_percent, s.phase_error, s.pause_reason, s.throughput_items_per_sec, s.memory_usage_mb, s.phase_progress_percent, s.phase_duration_seconds FROM scan_progress_summary s
JOIN volumes v ON s.volume_id = v.id
WHERE s.volume_id = $1 AND v.organization_id = $2
ORDER BY s.scan_started_at DESC, s.phase_started_at ASC
LIMIT $3 OFFSET $4
`

type GetScanProgressSummaryByVolumeParams struct {
	VolumeID       pgtype.Text `json:"volume_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) GetScanProgressSummaryByVolume(ctx context.Context, arg GetScanProgressSummaryByVolumeParams) ([]ScanProgressSummary, error) {
	rows, err := q.db.Query(ctx, getScanProgressSummaryByVolume,
		arg.VolumeID,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanProgressSummary{}
	for rows.Next() {
		var i ScanProgressSummary
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.ScanStatus,
			&i.ScanStartedAt,
			&i.ScanCompletedAt,
			&i.PhaseName,
			&i.PhaseStatus,
			&i.PhaseStartedAt,
			&i.PhaseCompletedAt,
			&i.ItemsProcessed,
			&i.ItemsTotal,
			&i.ItemsFailed,
			&i.CurrentItem,
			&i.ProgressPercent,
			&i.PhaseError,
			&i.PauseReason,
			&i.ThroughputItemsPerSec,
			&i.MemoryUsageMb,
			&i.PhaseProgressPercent,
			&i.PhaseDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeScanStats = `-- name: GetVolumeScanStats :many
SELECT volume_id, total_scans, successful_scans, failed_scans, running_scans, last_scan_started, last_scan_completed, avg_scan_duration_seconds FROM volume_scan_stats
ORDER BY last_scan_started DESC
`

func (q *Queries) GetVolumeScanStats(ctx context.Context) ([]VolumeScanStats, error) {
	rows, err := q.db.Query(ctx, getVolumeScanStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VolumeScanStats{}
	for rows.Next() {
		var i VolumeScanStats
		if err := rows.Scan(
			&i.VolumeID,
			&i.TotalScans,
			&i.SuccessfulScans,
			&i.FailedScans,
			&i.RunningScans,
			&i.LastScanStarted,
			&i.LastScanCompleted,
			&i.AvgScanDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeScanStatsByOrganization = `-- name: GetVolumeScanStatsByOrganization :many
SELECT v.volume_id, v.total_scans, v.successful_scans, v.failed_scans, v.running_scans, v.last_scan_started, v.last_scan_completed, v.avg_scan_duration_seconds FROM volume_scan_stats v
JOIN volumes vol ON v.volume_id = vol.id
WHERE vol.organization_id = $1
ORDER BY v.last_scan_started DESC
`

func (q *Queries) GetVolumeScanStatsByOrganization(ctx context.Context, organizationID pgtype.Int8) ([]VolumeScanStats, error) {
	rows, err := q.db.Query(ctx, getVolumeScanStatsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VolumeScanStats{}
	for rows.Next() {
		var i VolumeScanStats
		if err := rows.Scan(
			&i.VolumeID,
			&i.TotalScans,
			&i.SuccessfulScans,
			&i.FailedScans,
			&i.RunningScans,
			&i.LastScanStarted,
			&i.LastScanCompleted,
			&i.AvgScanDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeScanStatsByVolumeID = `-- name: GetVolumeScanStatsByVolumeID :one
SELECT volume_id, total_scans, successful_scans, failed_scans, running_scans, last_scan_started, last_scan_completed, avg_scan_duration_seconds FROM volume_scan_stats
WHERE volume_id = $1
`

func (q *Queries) GetVolumeScanStatsByVolumeID(ctx context.Context, volumeID pgtype.Text) (VolumeScanStats, error) {
	row := q.db.QueryRow(ctx, getVolumeScanStatsByVolumeID, volumeID)
	var i VolumeScanStats
	err := row.Scan(
		&i.VolumeID,
		&i.TotalScans,
		&i.SuccessfulScans,
		&i.FailedScans,
		&i.RunningScans,
		&i.LastScanStarted,
		&i.LastScanCompleted,
		&i.AvgScanDurationSeconds,
	)
	return i, err
}

const listScanJobs = `-- name: ListScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
ORDER BY COALESCE(started_at, created_at) DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListScanJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByOrganization = `-- name: ListScanJobsByOrganization :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE organization_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListScanJobsByOrganizationParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListScanJobsByOrganization(ctx context.Context, arg ListScanJobsByOrganizationParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByStatus = `-- name: ListScanJobsByStatus :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListScanJobsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListScanJobsByStatus(ctx context.Context, arg ListScanJobsByStatusParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByVolume = `-- name: ListScanJobsByVolume :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE volume_id = $1
ORDER BY started_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListScanJobsByVolumeParams struct {
	VolumeID pgtype.Text `json:"volume_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListScanJobsByVolume(ctx context.Context, arg ListScanJobsByVolumeParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByVolume, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByVolumeAndOrganization = `-- name: ListScanJobsByVolumeAndOrganization :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE volume_id = $1 AND organization_id = $2
ORDER BY started_at DESC
LIMIT $3 OFFSET $4
`

type ListScanJobsByVolumeAndOrganizationParams struct {
	VolumeID       pgtype.Text `json:"volume_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListScanJobsByVolumeAndOrganization(ctx context.Context, arg ListScanJobsByVolumeAndOrganizationParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByVolumeAndOrganization,
		arg.VolumeID,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInFlightJobsAsFailed = `-- name: MarkInFlightJobsAsFailed :many
UPDATE scan_jobs
SET
    status = 'failed',
    error_message = $1,
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE status IN ('running', 'pending')
RETURNING scan_id
`

func (q *Queries) MarkInFlightJobsAsFailed(ctx context.Context, errorMessage pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, markInFlightJobsAsFailed, errorMessage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInFlightJobsAsPaused = `-- name: MarkInFlightJobsAsPaused :many
UPDATE scan_jobs
SET
    status = 'paused',
    error_message = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE status IN ('running', 'pending')
RETURNING scan_id
`

func (q *Queries) MarkInFlightJobsAsPaused(ctx context.Context, errorMessage pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, markInFlightJobsAsPaused, errorMessage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleScanJobsAsFailed = `-- name: MarkStaleScanJobsAsFailed :many
UPDATE scan_jobs
SET
    status = 'failed',
    error_message = 'Scan job marked as stale after timeout (no heartbeat)',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'running'
  AND updated_at < (CURRENT_TIMESTAMP - INTERVAL '1 second' * $1)
RETURNING scan_id
`

func (q *Queries) MarkStaleScanJobsAsFailed(ctx context.Context, dollar_1 interface{}) ([]string, error) {
	rows, err := q.db.Query(ctx, markStaleScanJobsAsFailed, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanJobHeartbeat = `-- name: UpdateScanJobHeartbeat :exec
UPDATE scan_jobs
SET updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

func (q *Queries) UpdateScanJobHeartbeat(ctx context.Context, scanID string) error {
	_, err := q.db.Exec(ctx, updateScanJobHeartbeat, scanID)
	return err
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs
SET 
    scanned_files = $2,
    scanned_bytes = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type UpdateScanJobProgressParams struct {
	ScanID       string      `json:"scan_id"`
	ScannedFiles pgtype.Int8 `json:"scanned_files"`
	ScannedBytes pgtype.Int8 `json:"scanned_bytes"`
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateScanJobProgress, arg.ScanID, arg.ScannedFiles, arg.ScannedBytes)
	return err
}

const updateScanJobStatus = `-- name: UpdateScanJobStatus :exec
UPDATE scan_jobs
SET 
    status = $2,
    error_message = CASE WHEN $2 = 'failed' THEN $3 ELSE error_message END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN CURRENT_TIMESTAMP ELSE completed_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type UpdateScanJobStatusParams struct {
	ScanID       string      `json:"scan_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateScanJobStatus, arg.ScanID, arg.Status, arg.ErrorMessage)
	return err
}
