// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelScanJob = `-- name: CancelScanJob :exec
UPDATE scan_jobs
SET 
    status = 'cancelled',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

func (q *Queries) CancelScanJob(ctx context.Context, scanID string) error {
	_, err := q.db.Exec(ctx, cancelScanJob, scanID)
	return err
}

const completeScanJob = `-- name: CompleteScanJob :exec
UPDATE scan_jobs
SET 
    status = 'completed',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

func (q *Queries) CompleteScanJob(ctx context.Context, scanID string) error {
	_, err := q.db.Exec(ctx, completeScanJob, scanID)
	return err
}

const countScanJobsByStatus = `-- name: CountScanJobsByStatus :one
SELECT COUNT(*) FROM scan_jobs WHERE status = $1
`

func (q *Queries) CountScanJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countScanJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanJob = `-- name: CreateScanJob :one

INSERT INTO scan_jobs (
    scan_id, volume_id, status, started_at, organization_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id
`

type CreateScanJobParams struct {
	ScanID         string             `json:"scan_id"`
	VolumeID       pgtype.Text        `json:"volume_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
}

// Scan job management queries for PostgreSQL
func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, createScanJob,
		arg.ScanID,
		arg.VolumeID,
		arg.Status,
		arg.StartedAt,
		arg.OrganizationID,
	)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const deleteOldScanJobs = `-- name: DeleteOldScanJobs :exec
DELETE FROM scan_jobs
WHERE completed_at < $1
AND status IN ('completed', 'failed', 'cancelled')
`

func (q *Queries) DeleteOldScanJobs(ctx context.Context, completedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldScanJobs, completedAt)
	return err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs
SET 
    status = 'failed',
    error_message = $2,
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type FailScanJobParams struct {
	ScanID       string      `json:"scan_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.db.Exec(ctx, failScanJob, arg.ScanID, arg.ErrorMessage)
	return err
}

const getActiveScanJobs = `-- name: GetActiveScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status IN ('pending', 'running')
ORDER BY started_at ASC
`

func (q *Queries) GetActiveScanJobs(ctx context.Context) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getActiveScanJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveScanJobsByOrganization = `-- name: GetActiveScanJobsByOrganization :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status IN ('pending', 'running') AND organization_id = $1
ORDER BY started_at ASC
`

func (q *Queries) GetActiveScanJobsByOrganization(ctx context.Context, organizationID pgtype.Int8) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getActiveScanJobsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedScanJobs = `-- name: GetCompletedScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status = 'completed'
AND completed_at >= $1
ORDER BY completed_at DESC
LIMIT $2
`

type GetCompletedScanJobsParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetCompletedScanJobs(ctx context.Context, arg GetCompletedScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, getCompletedScanJobs, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanJobByScanID = `-- name: GetScanJobByScanID :one
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs WHERE scan_id = $1
`

func (q *Queries) GetScanJobByScanID(ctx context.Context, scanID string) (ScanJobs, error) {
	row := q.db.QueryRow(ctx, getScanJobByScanID, scanID)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listScanJobs = `-- name: ListScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListScanJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByOrganization = `-- name: ListScanJobsByOrganization :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE organization_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListScanJobsByOrganizationParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListScanJobsByOrganization(ctx context.Context, arg ListScanJobsByOrganizationParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByStatus = `-- name: ListScanJobsByStatus :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE status = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListScanJobsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListScanJobsByStatus(ctx context.Context, arg ListScanJobsByStatusParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByVolume = `-- name: ListScanJobsByVolume :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE volume_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListScanJobsByVolumeParams struct {
	VolumeID pgtype.Text `json:"volume_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListScanJobsByVolume(ctx context.Context, arg ListScanJobsByVolumeParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByVolume, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByVolumeAndOrganization = `-- name: ListScanJobsByVolumeAndOrganization :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at, organization_id FROM scan_jobs
WHERE volume_id = $1 AND organization_id = $2
ORDER BY started_at DESC
LIMIT $3 OFFSET $4
`

type ListScanJobsByVolumeAndOrganizationParams struct {
	VolumeID       pgtype.Text `json:"volume_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListScanJobsByVolumeAndOrganization(ctx context.Context, arg ListScanJobsByVolumeAndOrganizationParams) ([]ScanJobs, error) {
	rows, err := q.db.Query(ctx, listScanJobsByVolumeAndOrganization,
		arg.VolumeID,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInFlightJobsAsPaused = `-- name: MarkInFlightJobsAsPaused :many
UPDATE scan_jobs
SET 
    status = 'paused',
    error_message = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE status IN ('running', 'pending')
RETURNING scan_id
`

func (q *Queries) MarkInFlightJobsAsPaused(ctx context.Context, errorMessage pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, markInFlightJobsAsPaused, errorMessage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleScanJobsAsFailed = `-- name: MarkStaleScanJobsAsFailed :many
UPDATE scan_jobs
SET 
    status = 'failed',
    error_message = 'Scan job marked as stale after timeout',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'running'
  AND started_at < (CURRENT_TIMESTAMP - INTERVAL '1 second' * $1)
  AND started_at IS NOT NULL
RETURNING scan_id
`

func (q *Queries) MarkStaleScanJobsAsFailed(ctx context.Context, dollar_1 interface{}) ([]string, error) {
	rows, err := q.db.Query(ctx, markStaleScanJobsAsFailed, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs
SET 
    scanned_files = $2,
    scanned_bytes = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type UpdateScanJobProgressParams struct {
	ScanID       string      `json:"scan_id"`
	ScannedFiles pgtype.Int8 `json:"scanned_files"`
	ScannedBytes pgtype.Int8 `json:"scanned_bytes"`
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateScanJobProgress, arg.ScanID, arg.ScannedFiles, arg.ScannedBytes)
	return err
}

const updateScanJobStatus = `-- name: UpdateScanJobStatus :exec
UPDATE scan_jobs
SET 
    status = $2,
    error_message = CASE WHEN $2 = 'failed' THEN $3 ELSE error_message END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN CURRENT_TIMESTAMP ELSE completed_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE scan_id = $1
`

type UpdateScanJobStatusParams struct {
	ScanID       string      `json:"scan_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateScanJobStatus, arg.ScanID, arg.Status, arg.ErrorMessage)
	return err
}
