// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats_advanced.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldJobs = `-- name: CleanupOldJobs :exec
DELETE FROM stats_jobs
WHERE created_at < CURRENT_TIMESTAMP - ($1 || ' days')::interval
  AND status IN ('completed', 'failed', 'cancelled')
`

func (q *Queries) CleanupOldJobs(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, cleanupOldJobs, dollar_1)
	return err
}

const computeVolumeDailyStats = `-- name: ComputeVolumeDailyStats :exec

WITH current_stats AS (
    SELECT
        $1::text as volume_id,
        $2::date as date,
        COUNT(*) FILTER (WHERE is_dir = false) as total_files,
        SUM(size_bytes) as total_size
    FROM files
    WHERE volume_id = $1
),
previous_stats AS (
    SELECT
        total_files as prev_files,
        total_size_bytes as prev_size
    FROM daily_stats
    WHERE volume_id = $1
      AND date = $2::date - INTERVAL '1 day'
    LIMIT 1
),
file_changes AS (
    SELECT
        COUNT(*) FILTER (WHERE created_at::date = $2::date) as new_files,
        COUNT(*) FILTER (WHERE updated_at::date = $2::date AND created_at::date != $2::date) as modified_files
    FROM files
    WHERE volume_id = $1
)
INSERT INTO daily_stats (
    volume_id,
    date,
    total_size_bytes,
    total_files,
    size_change_bytes,
    growth_percent,
    new_files,
    modified_files,
    deleted_files
)
SELECT
    cs.volume_id,
    cs.date,
    cs.total_size,
    cs.total_files,
    cs.total_size - COALESCE(ps.prev_size, 0),
    CASE
        WHEN COALESCE(ps.prev_size, 0) > 0
        THEN ((cs.total_size - ps.prev_size)::float / ps.prev_size::float * 100)
        ELSE 0
    END,
    fc.new_files,
    fc.modified_files,
    GREATEST(0, COALESCE(ps.prev_files, 0) - cs.total_files)
FROM current_stats cs
CROSS JOIN file_changes fc
LEFT JOIN previous_stats ps ON true
ON CONFLICT (volume_id, date) DO UPDATE SET
    total_size_bytes = EXCLUDED.total_size_bytes,
    total_files = EXCLUDED.total_files,
    size_change_bytes = EXCLUDED.size_change_bytes,
    growth_percent = EXCLUDED.growth_percent,
    new_files = EXCLUDED.new_files,
    modified_files = EXCLUDED.modified_files,
    deleted_files = EXCLUDED.deleted_files,
    updated_at = CURRENT_TIMESTAMP
`

type ComputeVolumeDailyStatsParams struct {
	Column1 string      `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

// =============================================================================
// DAILY STATS COMPUTATION
// =============================================================================
func (q *Queries) ComputeVolumeDailyStats(ctx context.Context, arg ComputeVolumeDailyStatsParams) error {
	_, err := q.db.Exec(ctx, computeVolumeDailyStats, arg.Column1, arg.Column2)
	return err
}

const createStatsJob = `-- name: CreateStatsJob :one

INSERT INTO stats_jobs (
    job_id,
    job_type,
    volume_id,
    status,
    progress,
    organization_id
) VALUES (
    $1, $2, $3, 'pending', 0, $4
) RETURNING id, job_id, job_type, volume_id, status, progress, error_message, started_at, completed_at, duration_ms, records_processed, organization_id, created_at, updated_at
`

type CreateStatsJobParams struct {
	JobID          string      `json:"job_id"`
	JobType        string      `json:"job_type"`
	VolumeID       pgtype.Text `json:"volume_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
}

// =============================================================================
// JOB MANAGEMENT
// =============================================================================
func (q *Queries) CreateStatsJob(ctx context.Context, arg CreateStatsJobParams) (StatsJobs, error) {
	row := q.db.QueryRow(ctx, createStatsJob,
		arg.JobID,
		arg.JobType,
		arg.VolumeID,
		arg.OrganizationID,
	)
	var i StatsJobs
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.JobType,
		&i.VolumeID,
		&i.Status,
		&i.Progress,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.RecordsProcessed,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStatsForDate = `-- name: DeleteStatsForDate :exec
DELETE FROM daily_stats
WHERE volume_id = $1
  AND date = $2
`

type DeleteStatsForDateParams struct {
	VolumeID string      `json:"volume_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) DeleteStatsForDate(ctx context.Context, arg DeleteStatsForDateParams) error {
	_, err := q.db.Exec(ctx, deleteStatsForDate, arg.VolumeID, arg.Date)
	return err
}

const getCapacityPrediction = `-- name: GetCapacityPrediction :one

SELECT
    $1::text as volume_id,
    v.total_size_bytes as current_bytes,
    COALESCE(AVG(ds.size_change_bytes), 0)::bigint as avg_daily_growth,
    COALESCE(STDDEV(ds.size_change_bytes), 0)::bigint as growth_stddev,
    COUNT(ds.id)::bigint as data_points,
    (v.total_size_bytes + (COALESCE(AVG(ds.size_change_bytes), 0) * $3))::bigint as predicted_size,
    $3::int as days_ahead,
    CURRENT_TIMESTAMP as computed_at
FROM volumes v
LEFT JOIN daily_stats ds ON ds.volume_id = v.volume_id
    AND ds.date >= CURRENT_DATE - $2::int
    AND ds.size_change_bytes > 0
WHERE v.volume_id = $1
GROUP BY v.volume_id, v.total_size_bytes
`

type GetCapacityPredictionParams struct {
	Column1         string      `json:"column_1"`
	Column2         int32       `json:"column_2"`
	SizeChangeBytes pgtype.Int8 `json:"size_change_bytes"`
}

type GetCapacityPredictionRow struct {
	VolumeID       string      `json:"volume_id"`
	CurrentBytes   pgtype.Int8 `json:"current_bytes"`
	AvgDailyGrowth int64       `json:"avg_daily_growth"`
	GrowthStddev   int64       `json:"growth_stddev"`
	DataPoints     int64       `json:"data_points"`
	PredictedSize  int64       `json:"predicted_size"`
	DaysAhead      int32       `json:"days_ahead"`
	ComputedAt     interface{} `json:"computed_at"`
}

// =============================================================================
// CAPACITY PREDICTION
// =============================================================================
func (q *Queries) GetCapacityPrediction(ctx context.Context, arg GetCapacityPredictionParams) (GetCapacityPredictionRow, error) {
	row := q.db.QueryRow(ctx, getCapacityPrediction, arg.Column1, arg.Column2, arg.SizeChangeBytes)
	var i GetCapacityPredictionRow
	err := row.Scan(
		&i.VolumeID,
		&i.CurrentBytes,
		&i.AvgDailyGrowth,
		&i.GrowthStddev,
		&i.DataPoints,
		&i.PredictedSize,
		&i.DaysAhead,
		&i.ComputedAt,
	)
	return i, err
}

const getFileTypeDistribution = `-- name: GetFileTypeDistribution :many
SELECT
    LOWER(SUBSTRING(fi.name FROM '\.([^.]+)$')) as extension,
    COUNT(*) as file_count,
    SUM(fi.size_bytes) as total_bytes,
    AVG(fi.size_bytes)::bigint as avg_size
FROM files fi
WHERE fi.volume_id = $1
  AND fi.is_dir = false
GROUP BY extension
HAVING COUNT(*) > 0
ORDER BY total_bytes DESC
LIMIT $2
`

type GetFileTypeDistributionParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int32  `json:"limit"`
}

type GetFileTypeDistributionRow struct {
	Extension  string `json:"extension"`
	FileCount  int64  `json:"file_count"`
	TotalBytes int64  `json:"total_bytes"`
	AvgSize    int64  `json:"avg_size"`
}

func (q *Queries) GetFileTypeDistribution(ctx context.Context, arg GetFileTypeDistributionParams) ([]GetFileTypeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getFileTypeDistribution, arg.VolumeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFileTypeDistributionRow{}
	for rows.Next() {
		var i GetFileTypeDistributionRow
		if err := rows.Scan(
			&i.Extension,
			&i.FileCount,
			&i.TotalBytes,
			&i.AvgSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderGrowthTrends = `-- name: GetFolderGrowthTrends :many


SELECT
    f.id,
    f.volume_id,
    f.path,
    f.size_bytes_recursive as total_size,
    f.file_count_recursive as file_count,
    f.modified_at as updated_at,
    COALESCE(LAG(f.size_bytes_recursive) OVER (PARTITION BY f.path ORDER BY f.modified_at), 0) as previous_size,
    f.size_bytes_recursive - COALESCE(LAG(f.size_bytes_recursive) OVER (PARTITION BY f.path ORDER BY f.modified_at), 0) as size_change
FROM folders f
WHERE f.volume_id = $1
  AND f.modified_at >= $2
ORDER BY size_change DESC
LIMIT $3
`

type GetFolderGrowthTrendsParams struct {
	VolumeID   string             `json:"volume_id"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	Limit      int32              `json:"limit"`
}

type GetFolderGrowthTrendsRow struct {
	ID           int64              `json:"id"`
	VolumeID     string             `json:"volume_id"`
	Path         string             `json:"path"`
	TotalSize    pgtype.Int8        `json:"total_size"`
	FileCount    pgtype.Int4        `json:"file_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PreviousSize interface{}        `json:"previous_size"`
	SizeChange   int32              `json:"size_change"`
}

// Advanced statistics and analytics queries for PostgreSQL
// =============================================================================
// FOLDER GROWTH AND TRENDS
// =============================================================================
func (q *Queries) GetFolderGrowthTrends(ctx context.Context, arg GetFolderGrowthTrendsParams) ([]GetFolderGrowthTrendsRow, error) {
	rows, err := q.db.Query(ctx, getFolderGrowthTrends, arg.VolumeID, arg.ModifiedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFolderGrowthTrendsRow{}
	for rows.Next() {
		var i GetFolderGrowthTrendsRow
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.Path,
			&i.TotalSize,
			&i.FileCount,
			&i.UpdatedAt,
			&i.PreviousSize,
			&i.SizeChange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistoricalStats = `-- name: GetHistoricalStats :many
SELECT
    date,
    total_size_bytes,
    total_files,
    size_change_bytes,
    growth_percent,
    new_files,
    deleted_files,
    modified_files,
    media_files,
    document_files,
    code_files,
    archive_files,
    other_files
FROM daily_stats
WHERE volume_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type GetHistoricalStatsParams struct {
	VolumeID string      `json:"volume_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type GetHistoricalStatsRow struct {
	Date            pgtype.Date    `json:"date"`
	TotalSizeBytes  pgtype.Int8    `json:"total_size_bytes"`
	TotalFiles      pgtype.Int8    `json:"total_files"`
	SizeChangeBytes pgtype.Int8    `json:"size_change_bytes"`
	GrowthPercent   pgtype.Numeric `json:"growth_percent"`
	NewFiles        pgtype.Int8    `json:"new_files"`
	DeletedFiles    pgtype.Int8    `json:"deleted_files"`
	ModifiedFiles   pgtype.Int8    `json:"modified_files"`
	MediaFiles      pgtype.Int8    `json:"media_files"`
	DocumentFiles   pgtype.Int8    `json:"document_files"`
	CodeFiles       pgtype.Int8    `json:"code_files"`
	ArchiveFiles    pgtype.Int8    `json:"archive_files"`
	OtherFiles      pgtype.Int8    `json:"other_files"`
}

func (q *Queries) GetHistoricalStats(ctx context.Context, arg GetHistoricalStatsParams) ([]GetHistoricalStatsRow, error) {
	rows, err := q.db.Query(ctx, getHistoricalStats, arg.VolumeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHistoricalStatsRow{}
	for rows.Next() {
		var i GetHistoricalStatsRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalSizeBytes,
			&i.TotalFiles,
			&i.SizeChangeBytes,
			&i.GrowthPercent,
			&i.NewFiles,
			&i.DeletedFiles,
			&i.ModifiedFiles,
			&i.MediaFiles,
			&i.DocumentFiles,
			&i.CodeFiles,
			&i.ArchiveFiles,
			&i.OtherFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobMetrics = `-- name: GetJobMetrics :one
SELECT
    COUNT(*) as total_jobs,
    COUNT(*) FILTER (WHERE status = 'completed') as successful_jobs,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_jobs,
    COUNT(*) FILTER (WHERE status = 'running') as running_jobs,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_jobs,
    AVG(duration_ms) FILTER (WHERE status = 'completed')::bigint as avg_duration_ms,
    SUM(records_processed) as total_records_processed
FROM stats_jobs
WHERE job_type = $1
  AND created_at >= CURRENT_TIMESTAMP - ($2 || ' days')::interval
`

type GetJobMetricsParams struct {
	JobType string      `json:"job_type"`
	Column2 pgtype.Text `json:"column_2"`
}

type GetJobMetricsRow struct {
	TotalJobs             int64 `json:"total_jobs"`
	SuccessfulJobs        int64 `json:"successful_jobs"`
	FailedJobs            int64 `json:"failed_jobs"`
	RunningJobs           int64 `json:"running_jobs"`
	PendingJobs           int64 `json:"pending_jobs"`
	AvgDurationMs         int64 `json:"avg_duration_ms"`
	TotalRecordsProcessed int64 `json:"total_records_processed"`
}

func (q *Queries) GetJobMetrics(ctx context.Context, arg GetJobMetricsParams) (GetJobMetricsRow, error) {
	row := q.db.QueryRow(ctx, getJobMetrics, arg.JobType, arg.Column2)
	var i GetJobMetricsRow
	err := row.Scan(
		&i.TotalJobs,
		&i.SuccessfulJobs,
		&i.FailedJobs,
		&i.RunningJobs,
		&i.PendingJobs,
		&i.AvgDurationMs,
		&i.TotalRecordsProcessed,
	)
	return i, err
}

const getJobStatus = `-- name: GetJobStatus :one
SELECT id, job_id, job_type, volume_id, status, progress, error_message, started_at, completed_at, duration_ms, records_processed, organization_id, created_at, updated_at FROM stats_jobs
WHERE job_id = $1
`

func (q *Queries) GetJobStatus(ctx context.Context, jobID string) (StatsJobs, error) {
	row := q.db.QueryRow(ctx, getJobStatus, jobID)
	var i StatsJobs
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.JobType,
		&i.VolumeID,
		&i.Status,
		&i.Progress,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.RecordsProcessed,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobStatusByID = `-- name: GetJobStatusByID :one
SELECT id, job_id, job_type, volume_id, status, progress, error_message, started_at, completed_at, duration_ms, records_processed, organization_id, created_at, updated_at FROM stats_jobs
WHERE id = $1
`

func (q *Queries) GetJobStatusByID(ctx context.Context, id int64) (StatsJobs, error) {
	row := q.db.QueryRow(ctx, getJobStatusByID, id)
	var i StatsJobs
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.JobType,
		&i.VolumeID,
		&i.Status,
		&i.Progress,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.RecordsProcessed,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestVolumeStats = `-- name: GetLatestVolumeStats :one

SELECT
    COUNT(DISTINCT v.volume_id) as total_volumes,
    COUNT(DISTINCT v.volume_id) FILTER (WHERE v.is_active = true) as active_volumes,
    COUNT(DISTINCT v.volume_id) FILTER (WHERE v.last_scan_at IS NOT NULL) as scanned_volumes,
    COALESCE(SUM(v.total_size_bytes), 0) as total_bytes,
    COALESCE(SUM((SELECT COUNT(*) FROM files f WHERE f.volume_id = v.volume_id AND f.is_dir = false)), 0) as total_files
FROM volumes v
WHERE ($1::text IS NULL OR v.volume_id = $1)
`

type GetLatestVolumeStatsRow struct {
	TotalVolumes   int64       `json:"total_volumes"`
	ActiveVolumes  int64       `json:"active_volumes"`
	ScannedVolumes int64       `json:"scanned_volumes"`
	TotalBytes     interface{} `json:"total_bytes"`
	TotalFiles     interface{} `json:"total_files"`
}

// =============================================================================
// VOLUME STATISTICS
// =============================================================================
func (q *Queries) GetLatestVolumeStats(ctx context.Context, dollar_1 string) (GetLatestVolumeStatsRow, error) {
	row := q.db.QueryRow(ctx, getLatestVolumeStats, dollar_1)
	var i GetLatestVolumeStatsRow
	err := row.Scan(
		&i.TotalVolumes,
		&i.ActiveVolumes,
		&i.ScannedVolumes,
		&i.TotalBytes,
		&i.TotalFiles,
	)
	return i, err
}

const getMediaKindComposition = `-- name: GetMediaKindComposition :many

SELECT
    fm.raw_metadata->>'mediaKind' as media_kind,
    COUNT(*) as file_count,
    SUM(fi.size_bytes) as total_bytes,
    AVG(fi.size_bytes)::bigint as avg_size,
    MIN(fi.size_bytes) as min_size,
    MAX(fi.size_bytes) as max_size
FROM file_metadata fm
INNER JOIN files fi ON fm.file_id = fi.id
WHERE fi.volume_id = $1
  AND fm.raw_metadata->>'mediaKind' IS NOT NULL
  AND fm.raw_metadata->>'mediaKind' != ''
GROUP BY fm.raw_metadata->>'mediaKind'
ORDER BY total_bytes DESC
`

type GetMediaKindCompositionRow struct {
	MediaKind  interface{} `json:"media_kind"`
	FileCount  int64       `json:"file_count"`
	TotalBytes int64       `json:"total_bytes"`
	AvgSize    int64       `json:"avg_size"`
	MinSize    interface{} `json:"min_size"`
	MaxSize    interface{} `json:"max_size"`
}

// =============================================================================
// MEDIA AND FILE TYPE ANALYSIS
// =============================================================================
func (q *Queries) GetMediaKindComposition(ctx context.Context, volumeID string) ([]GetMediaKindCompositionRow, error) {
	rows, err := q.db.Query(ctx, getMediaKindComposition, volumeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMediaKindCompositionRow{}
	for rows.Next() {
		var i GetMediaKindCompositionRow
		if err := rows.Scan(
			&i.MediaKind,
			&i.FileCount,
			&i.TotalBytes,
			&i.AvgSize,
			&i.MinSize,
			&i.MaxSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMissingStatsDates = `-- name: GetMissingStatsDates :many
WITH date_range AS (
    SELECT generate_series(
        $2::date,
        $3::date,
        '1 day'::interval
    )::date as date
)
SELECT dr.date
FROM date_range dr
LEFT JOIN daily_stats ds ON ds.volume_id = $1 AND ds.date = dr.date
WHERE ds.id IS NULL
ORDER BY dr.date
`

type GetMissingStatsDatesParams struct {
	VolumeID string      `json:"volume_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
}

func (q *Queries) GetMissingStatsDates(ctx context.Context, arg GetMissingStatsDatesParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, getMissingStatsDates, arg.VolumeID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var date pgtype.Date
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentJobs = `-- name: GetRecentJobs :many
SELECT id, job_id, job_type, volume_id, status, progress, error_message, started_at, completed_at, duration_ms, records_processed, organization_id, created_at, updated_at FROM stats_jobs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentJobs(ctx context.Context, limit int32) ([]StatsJobs, error) {
	rows, err := q.db.Query(ctx, getRecentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsJobs{}
	for rows.Next() {
		var i StatsJobs
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.JobType,
			&i.VolumeID,
			&i.Status,
			&i.Progress,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.RecordsProcessed,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentJobsByType = `-- name: GetRecentJobsByType :many
SELECT id, job_id, job_type, volume_id, status, progress, error_message, started_at, completed_at, duration_ms, records_processed, organization_id, created_at, updated_at FROM stats_jobs
WHERE job_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentJobsByTypeParams struct {
	JobType string `json:"job_type"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetRecentJobsByType(ctx context.Context, arg GetRecentJobsByTypeParams) ([]StatsJobs, error) {
	rows, err := q.db.Query(ctx, getRecentJobsByType, arg.JobType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsJobs{}
	for rows.Next() {
		var i StatsJobs
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.JobType,
			&i.VolumeID,
			&i.Status,
			&i.Progress,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.RecordsProcessed,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageGrowthTrend = `-- name: GetStorageGrowthTrend :many
SELECT
    date,
    total_size_bytes,
    size_change_bytes,
    growth_percent,
    total_files,
    new_files,
    deleted_files,
    modified_files
FROM daily_stats
WHERE volume_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type GetStorageGrowthTrendParams struct {
	VolumeID string      `json:"volume_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type GetStorageGrowthTrendRow struct {
	Date            pgtype.Date    `json:"date"`
	TotalSizeBytes  pgtype.Int8    `json:"total_size_bytes"`
	SizeChangeBytes pgtype.Int8    `json:"size_change_bytes"`
	GrowthPercent   pgtype.Numeric `json:"growth_percent"`
	TotalFiles      pgtype.Int8    `json:"total_files"`
	NewFiles        pgtype.Int8    `json:"new_files"`
	DeletedFiles    pgtype.Int8    `json:"deleted_files"`
	ModifiedFiles   pgtype.Int8    `json:"modified_files"`
}

func (q *Queries) GetStorageGrowthTrend(ctx context.Context, arg GetStorageGrowthTrendParams) ([]GetStorageGrowthTrendRow, error) {
	rows, err := q.db.Query(ctx, getStorageGrowthTrend, arg.VolumeID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStorageGrowthTrendRow{}
	for rows.Next() {
		var i GetStorageGrowthTrendRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalSizeBytes,
			&i.SizeChangeBytes,
			&i.GrowthPercent,
			&i.TotalFiles,
			&i.NewFiles,
			&i.DeletedFiles,
			&i.ModifiedFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopGrowingFolders = `-- name: GetTopGrowingFolders :many
WITH folder_changes AS (
    SELECT
        f.id,
        f.volume_id,
        f.path,
        f.size_bytes_recursive as current_size,
        f.file_count_recursive as file_count,
        f.modified_at as updated_at,
        COALESCE(LAG(f.size_bytes_recursive) OVER (PARTITION BY f.path ORDER BY f.modified_at), f.size_bytes_recursive) as previous_size
    FROM folders f
    WHERE f.volume_id = $1
      AND f.modified_at >= $2
)
SELECT
    id,
    volume_id,
    path,
    current_size,
    file_count,
    updated_at,
    previous_size,
    (current_size - previous_size) as size_change,
    CASE
        WHEN previous_size > 0 THEN ((current_size - previous_size)::float / previous_size::float * 100)
        ELSE 0
    END as growth_percent
FROM folder_changes
WHERE (current_size - previous_size) > 0
ORDER BY (current_size - previous_size) DESC
LIMIT $3
`

type GetTopGrowingFoldersParams struct {
	VolumeID   string             `json:"volume_id"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	Limit      int32              `json:"limit"`
}

type GetTopGrowingFoldersRow struct {
	ID            int64       `json:"id"`
	VolumeID      string      `json:"volume_id"`
	Path          string      `json:"path"`
	CurrentSize   pgtype.Int8 `json:"current_size"`
	FileCount     pgtype.Int4 `json:"file_count"`
	UpdatedAt     time.Time   `json:"updated_at"`
	PreviousSize  pgtype.Int8 `json:"previous_size"`
	SizeChange    int32       `json:"size_change"`
	GrowthPercent int32       `json:"growth_percent"`
}

func (q *Queries) GetTopGrowingFolders(ctx context.Context, arg GetTopGrowingFoldersParams) ([]GetTopGrowingFoldersRow, error) {
	rows, err := q.db.Query(ctx, getTopGrowingFolders, arg.VolumeID, arg.ModifiedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopGrowingFoldersRow{}
	for rows.Next() {
		var i GetTopGrowingFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.VolumeID,
			&i.Path,
			&i.CurrentSize,
			&i.FileCount,
			&i.UpdatedAt,
			&i.PreviousSize,
			&i.SizeChange,
			&i.GrowthPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrendAnalysis = `-- name: GetTrendAnalysis :one

WITH stats_window AS (
    SELECT
        date,
        total_size_bytes,
        total_files,
        size_change_bytes,
        growth_percent
    FROM daily_stats
    WHERE volume_id = $1
      AND date >= CURRENT_DATE - $2::int
    ORDER BY date DESC
)
SELECT
    $1 as volume_id,
    COUNT(*) as data_points,
    MAX(date) as latest_date,
    SUM(total_files) as total_files,
    SUM(total_size_bytes) as total_bytes,
    AVG(size_change_bytes)::bigint as avg_daily_change,
    AVG(growth_percent)::numeric as avg_growth_rate,
    MAX(size_change_bytes) as max_daily_change,
    MIN(size_change_bytes) as min_daily_change,
    STDDEV(size_change_bytes)::bigint as change_stddev
FROM stats_window
`

type GetTrendAnalysisParams struct {
	VolumeID string `json:"volume_id"`
	Column2  int32  `json:"column_2"`
}

type GetTrendAnalysisRow struct {
	VolumeID       interface{}    `json:"volume_id"`
	DataPoints     int64          `json:"data_points"`
	LatestDate     interface{}    `json:"latest_date"`
	TotalFiles     int64          `json:"total_files"`
	TotalBytes     int64          `json:"total_bytes"`
	AvgDailyChange int64          `json:"avg_daily_change"`
	AvgGrowthRate  pgtype.Numeric `json:"avg_growth_rate"`
	MaxDailyChange interface{}    `json:"max_daily_change"`
	MinDailyChange interface{}    `json:"min_daily_change"`
	ChangeStddev   int64          `json:"change_stddev"`
}

// =============================================================================
// TREND ANALYSIS
// =============================================================================
func (q *Queries) GetTrendAnalysis(ctx context.Context, arg GetTrendAnalysisParams) (GetTrendAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getTrendAnalysis, arg.VolumeID, arg.Column2)
	var i GetTrendAnalysisRow
	err := row.Scan(
		&i.VolumeID,
		&i.DataPoints,
		&i.LatestDate,
		&i.TotalFiles,
		&i.TotalBytes,
		&i.AvgDailyChange,
		&i.AvgGrowthRate,
		&i.MaxDailyChange,
		&i.MinDailyChange,
		&i.ChangeStddev,
	)
	return i, err
}

const getVolumeComparison = `-- name: GetVolumeComparison :many
SELECT
    v.volume_id,
    v.display_name as name,
    COALESCE(v.total_size_bytes, 0) as total_bytes,
    COALESCE((SELECT COUNT(*) FROM files f WHERE f.volume_id = v.volume_id AND f.is_dir = false), 0) as total_files,
    v.last_scan_at as last_scanned,
    COALESCE(ds.growth_percent, 0) as growth_rate,
    COALESCE(ds.size_change_bytes, 0) as recent_change
FROM volumes v
LEFT JOIN LATERAL (
    SELECT growth_percent, size_change_bytes
    FROM daily_stats
    WHERE volume_id = v.volume_id
    ORDER BY date DESC
    LIMIT 1
) ds ON true
WHERE v.is_active = true
ORDER BY total_bytes DESC
LIMIT $1
`

type GetVolumeComparisonRow struct {
	VolumeID     string             `json:"volume_id"`
	Name         pgtype.Text        `json:"name"`
	TotalBytes   int64              `json:"total_bytes"`
	TotalFiles   interface{}        `json:"total_files"`
	LastScanned  pgtype.Timestamptz `json:"last_scanned"`
	GrowthRate   pgtype.Numeric     `json:"growth_rate"`
	RecentChange int64              `json:"recent_change"`
}

func (q *Queries) GetVolumeComparison(ctx context.Context, limit int32) ([]GetVolumeComparisonRow, error) {
	rows, err := q.db.Query(ctx, getVolumeComparison, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVolumeComparisonRow{}
	for rows.Next() {
		var i GetVolumeComparisonRow
		if err := rows.Scan(
			&i.VolumeID,
			&i.Name,
			&i.TotalBytes,
			&i.TotalFiles,
			&i.LastScanned,
			&i.GrowthRate,
			&i.RecentChange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeStatsSummary = `-- name: GetVolumeStatsSummary :one

SELECT
    v.volume_id,
    v.display_name as name,
    COALESCE(v.total_size_bytes, 0) as total_bytes,
    COALESCE((SELECT COUNT(*) FROM files f WHERE f.volume_id = v.volume_id AND f.is_dir = false), 0) as total_files,
    v.last_scan_at as last_scanned,
    CASE
        WHEN v.is_active THEN 'active'::text
        ELSE 'inactive'::text
    END as status,
    COALESCE(latest.growth_percent, 0) as recent_growth_rate,
    COALESCE(latest.size_change_bytes, 0) as recent_size_change,
    COALESCE(latest.date, CURRENT_DATE) as latest_stats_date
FROM volumes v
LEFT JOIN LATERAL (
    SELECT date, growth_percent, size_change_bytes
    FROM daily_stats
    WHERE volume_id = v.volume_id
    ORDER BY date DESC
    LIMIT 1
) latest ON true
WHERE v.volume_id = $1
`

type GetVolumeStatsSummaryRow struct {
	VolumeID         string             `json:"volume_id"`
	Name             pgtype.Text        `json:"name"`
	TotalBytes       int64              `json:"total_bytes"`
	TotalFiles       interface{}        `json:"total_files"`
	LastScanned      pgtype.Timestamptz `json:"last_scanned"`
	Status           string             `json:"status"`
	RecentGrowthRate pgtype.Numeric     `json:"recent_growth_rate"`
	RecentSizeChange int64              `json:"recent_size_change"`
	LatestStatsDate  pgtype.Date        `json:"latest_stats_date"`
}

// =============================================================================
// VOLUME STATISTICS AGGREGATIONS
// =============================================================================
func (q *Queries) GetVolumeStatsSummary(ctx context.Context, volumeID string) (GetVolumeStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getVolumeStatsSummary, volumeID)
	var i GetVolumeStatsSummaryRow
	err := row.Scan(
		&i.VolumeID,
		&i.Name,
		&i.TotalBytes,
		&i.TotalFiles,
		&i.LastScanned,
		&i.Status,
		&i.RecentGrowthRate,
		&i.RecentSizeChange,
		&i.LatestStatsDate,
	)
	return i, err
}

const refreshDailySummaryView = `-- name: RefreshDailySummaryView :exec

SELECT 1
`

// =============================================================================
// MATERIALIZED VIEW REFRESH
// =============================================================================
// This would refresh a materialized view if one existed
// For now, this is a no-op that can be implemented when materialized views are added
func (q *Queries) RefreshDailySummaryView(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshDailySummaryView)
	return err
}

const updateStatsJob = `-- name: UpdateStatsJob :exec
UPDATE stats_jobs
SET
    status = $2,
    progress = $3,
    error_message = $4,
    updated_at = CURRENT_TIMESTAMP,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN CURRENT_TIMESTAMP ELSE completed_at END,
    duration_ms = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - started_at)) * 1000 ELSE duration_ms END
WHERE job_id = $1
`

type UpdateStatsJobParams struct {
	JobID        string      `json:"job_id"`
	Status       string      `json:"status"`
	Progress     pgtype.Int4 `json:"progress"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateStatsJob(ctx context.Context, arg UpdateStatsJobParams) error {
	_, err := q.db.Exec(ctx, updateStatsJob,
		arg.JobID,
		arg.Status,
		arg.Progress,
		arg.ErrorMessage,
	)
	return err
}

const updateStatsJobProgress = `-- name: UpdateStatsJobProgress :exec
UPDATE stats_jobs
SET
    progress = $2,
    records_processed = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE job_id = $1
`

type UpdateStatsJobProgressParams struct {
	JobID            string      `json:"job_id"`
	Progress         pgtype.Int4 `json:"progress"`
	RecordsProcessed pgtype.Int8 `json:"records_processed"`
}

func (q *Queries) UpdateStatsJobProgress(ctx context.Context, arg UpdateStatsJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateStatsJobProgress, arg.JobID, arg.Progress, arg.RecordsProcessed)
	return err
}
