// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM user_sessions 
WHERE expires_at < CURRENT_TIMESTAMP OR revoked_at IS NOT NULL
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, role, status,
    first_name, last_name, display_name, timezone, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, username, email, password_hash, role, status, first_name, last_name, display_name, avatar_url, timezone, password_reset_token, password_reset_expires, email_verification_token, email_verified_at, last_login_at, login_attempts, locked_until, created_at, updated_at, created_by, organization_id
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Role         UserRole    `json:"role"`
	Status       string      `json:"status"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	DisplayName  pgtype.Text `json:"display_name"`
	Timezone     pgtype.Text `json:"timezone"`
	CreatedBy    pgtype.Text `json:"created_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Timezone,
		arg.CreatedBy,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.EmailVerificationToken,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.OrganizationID,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
    user_id, session_token, jwt_token_id, device_info,
    ip_address, user_agent, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, session_token, jwt_token_id, device_info, ip_address, user_agent, created_at, expires_at, last_used_at, revoked_at, is_active
`

type CreateUserSessionParams struct {
	UserID       int64              `json:"user_id"`
	SessionToken string             `json:"session_token"`
	JwtTokenID   string             `json:"jwt_token_id"`
	DeviceInfo   []byte             `json:"device_info"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// User Sessions
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSessions, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.SessionToken,
		arg.JwtTokenID,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.JwtTokenID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_preferences 
WHERE user_id = $1 AND preference_key = $2
`

type DeleteUserPreferenceParams struct {
	UserID        int64  `json:"user_id"`
	PreferenceKey string `json:"preference_key"`
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteUserPreference, arg.UserID, arg.PreferenceKey)
	return err
}

const getAllUserPreferences = `-- name: GetAllUserPreferences :many
SELECT id, user_id, preference_key, preference_value, created_at, updated_at FROM user_preferences 
WHERE user_id = $1
ORDER BY preference_key
`

func (q *Queries) GetAllUserPreferences(ctx context.Context, userID int64) ([]UserPreferences, error) {
	rows, err := q.db.Query(ctx, getAllUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPreferences{}
	for rows.Next() {
		var i UserPreferences
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PreferenceKey,
			&i.PreferenceValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivityLog = `-- name: GetUserActivityLog :many
SELECT id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, session_id, created_at FROM user_activity_log 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserActivityLogParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetUserActivityLog(ctx context.Context, arg GetUserActivityLogParams) ([]UserActivityLog, error) {
	rows, err := q.db.Query(ctx, getUserActivityLog, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivityLog{}
	for rows.Next() {
		var i UserActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, status, first_name, last_name, display_name, avatar_url, timezone, password_reset_token, password_reset_expires, email_verification_token, email_verified_at, last_login_at, login_attempts, locked_until, created_at, updated_at, created_by, organization_id FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.EmailVerificationToken,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.OrganizationID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, status, first_name, last_name, display_name, avatar_url, timezone, password_reset_token, password_reset_expires, email_verification_token, email_verified_at, last_login_at, login_attempts, locked_until, created_at, updated_at, created_by, organization_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.EmailVerificationToken,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.OrganizationID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, status, first_name, last_name, display_name, avatar_url, timezone, password_reset_token, password_reset_expires, email_verification_token, email_verified_at, last_login_at, login_attempts, locked_until, created_at, updated_at, created_by, organization_id FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.EmailVerificationToken,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.OrganizationID,
	)
	return i, err
}

const getUserPreference = `-- name: GetUserPreference :one
SELECT id, user_id, preference_key, preference_value, created_at, updated_at FROM user_preferences 
WHERE user_id = $1 AND preference_key = $2
`

type GetUserPreferenceParams struct {
	UserID        int64  `json:"user_id"`
	PreferenceKey string `json:"preference_key"`
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (UserPreferences, error) {
	row := q.db.QueryRow(ctx, getUserPreference, arg.UserID, arg.PreferenceKey)
	var i UserPreferences
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferenceKey,
		&i.PreferenceValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT id, user_id, session_token, jwt_token_id, device_info, ip_address, user_agent, created_at, expires_at, last_used_at, revoked_at, is_active FROM user_sessions 
WHERE session_token = $1 AND is_active = TRUE AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetUserSession(ctx context.Context, sessionToken string) (UserSessions, error) {
	row := q.db.QueryRow(ctx, getUserSession, sessionToken)
	var i UserSessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.JwtTokenID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserSessionByJTI = `-- name: GetUserSessionByJTI :one
SELECT id, user_id, session_token, jwt_token_id, device_info, ip_address, user_agent, created_at, expires_at, last_used_at, revoked_at, is_active FROM user_sessions 
WHERE jwt_token_id = $1 AND is_active = TRUE
`

func (q *Queries) GetUserSessionByJTI(ctx context.Context, jwtTokenID string) (UserSessions, error) {
	row := q.db.QueryRow(ctx, getUserSessionByJTI, jwtTokenID)
	var i UserSessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.JwtTokenID,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.IsActive,
	)
	return i, err
}

const incrementLoginAttempts = `-- name: IncrementLoginAttempts :exec
UPDATE users SET 
    login_attempts = login_attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementLoginAttempts, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, status, first_name, last_name, display_name, avatar_url, timezone, password_reset_token, password_reset_expires, email_verification_token, email_verified_at, last_login_at, login_attempts, locked_until, created_at, updated_at, created_by, organization_id FROM users 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.PasswordResetToken,
			&i.PasswordResetExpires,
			&i.EmailVerificationToken,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.LoginAttempts,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users SET 
    locked_until = $2,
    status = 'locked'
WHERE id = $1
`

type LockUserParams struct {
	ID          int64              `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const logUserActivity = `-- name: LogUserActivity :one
INSERT INTO user_activity_log (
    user_id, action, resource_type, resource_id,
    details, ip_address, user_agent, session_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, session_id, created_at
`

type LogUserActivityParams struct {
	UserID       pgtype.Int8 `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType pgtype.Text `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Details      []byte      `json:"details"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	SessionID    pgtype.Int8 `json:"session_id"`
}

// User Activity Log
func (q *Queries) LogUserActivity(ctx context.Context, arg LogUserActivityParams) (UserActivityLog, error) {
	row := q.db.QueryRow(ctx, logUserActivity,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.SessionID,
	)
	var i UserActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions SET 
    is_active = FALSE,
    revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE user_sessions SET 
    is_active = FALSE,
    revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RevokeUserSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeUserSession, id)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users SET 
    password_reset_token = $2,
    password_reset_expires = $3
WHERE id = $1
`

type SetPasswordResetTokenParams struct {
	ID                   int64              `json:"id"`
	PasswordResetToken   pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.ID, arg.PasswordResetToken, arg.PasswordResetExpires)
	return err
}

const setUserPreference = `-- name: SetUserPreference :one
INSERT INTO user_preferences (user_id, preference_key, preference_value)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, preference_key) 
DO UPDATE SET preference_value = EXCLUDED.preference_value
RETURNING id, user_id, preference_key, preference_value, created_at, updated_at
`

type SetUserPreferenceParams struct {
	UserID          int64  `json:"user_id"`
	PreferenceKey   string `json:"preference_key"`
	PreferenceValue []byte `json:"preference_value"`
}

// User Preferences
func (q *Queries) SetUserPreference(ctx context.Context, arg SetUserPreferenceParams) (UserPreferences, error) {
	row := q.db.QueryRow(ctx, setUserPreference, arg.UserID, arg.PreferenceKey, arg.PreferenceValue)
	var i UserPreferences
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PreferenceKey,
		&i.PreferenceValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE user_sessions SET last_used_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    first_name = COALESCE($3, first_name),
    last_name = COALESCE($4, last_name),
    display_name = COALESCE($5, display_name),
    timezone = COALESCE($6, timezone),
    role = COALESCE($7, role),
    status = COALESCE($8, status)
WHERE id = $1
RETURNING id, username, email, password_hash, role, status, first_name, last_name, display_name, avatar_url, timezone, password_reset_token, password_reset_expires, email_verification_token, email_verified_at, last_login_at, login_attempts, locked_until, created_at, updated_at, created_by, organization_id
`

type UpdateUserParams struct {
	ID          int64       `json:"id"`
	Email       string      `json:"email"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	DisplayName pgtype.Text `json:"display_name"`
	Timezone    pgtype.Text `json:"timezone"`
	Role        UserRole    `json:"role"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Timezone,
		arg.Role,
		arg.Status,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.EmailVerificationToken,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.OrganizationID,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET 
    last_login_at = CURRENT_TIMESTAMP,
    login_attempts = 0,
    locked_until = NULL
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET 
    password_hash = $2,
    password_reset_token = NULL,
    password_reset_expires = NULL
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users SET 
    email_verified_at = CURRENT_TIMESTAMP,
    email_verification_token = NULL
WHERE id = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, verifyEmail, id)
	return err
}
