// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: file_metadata.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countOldFileMetadata = `-- name: CountOldFileMetadata :one
SELECT COUNT(*) FROM file_metadata 
WHERE extracted_at < ?
  AND extracted_at IS NOT NULL
`

func (q *Queries) CountOldFileMetadata(ctx context.Context, extractedAt sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.countOldFileMetadataStmt, countOldFileMetadata, extractedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFileMetadata = `-- name: CreateFileMetadata :one

INSERT INTO file_metadata (
    file_id, raw_metadata, extracted_at, extractor_version, 
    extraction_duration_ms, error_message
) VALUES (
    ?, ?, ?, ?, ?, ?
) RETURNING id, file_id, raw_metadata, extracted_at, extractor_version, extraction_duration_ms, error_message
`

type CreateFileMetadataParams struct {
	FileID               int64          `json:"file_id"`
	RawMetadata          string         `json:"raw_metadata"`
	ExtractedAt          sql.NullString `json:"extracted_at"`
	ExtractorVersion     sql.NullString `json:"extractor_version"`
	ExtractionDurationMs sql.NullInt64  `json:"extraction_duration_ms"`
	ErrorMessage         sql.NullString `json:"error_message"`
}

// File metadata queries for SQLite
func (q *Queries) CreateFileMetadata(ctx context.Context, arg CreateFileMetadataParams) (FileMetadata, error) {
	row := q.queryRow(ctx, q.createFileMetadataStmt, createFileMetadata,
		arg.FileID,
		arg.RawMetadata,
		arg.ExtractedAt,
		arg.ExtractorVersion,
		arg.ExtractionDurationMs,
		arg.ErrorMessage,
	)
	var i FileMetadata
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.RawMetadata,
		&i.ExtractedAt,
		&i.ExtractorVersion,
		&i.ExtractionDurationMs,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteFileMetadata = `-- name: DeleteFileMetadata :exec
DELETE FROM file_metadata WHERE file_id = ?
`

func (q *Queries) DeleteFileMetadata(ctx context.Context, fileID int64) error {
	_, err := q.exec(ctx, q.deleteFileMetadataStmt, deleteFileMetadata, fileID)
	return err
}

const deleteFileMetadataByVolume = `-- name: DeleteFileMetadataByVolume :exec
DELETE FROM file_metadata 
WHERE file_id IN (
    SELECT id FROM files WHERE volume_id = ?
)
`

func (q *Queries) DeleteFileMetadataByVolume(ctx context.Context, volumeID string) error {
	_, err := q.exec(ctx, q.deleteFileMetadataByVolumeStmt, deleteFileMetadataByVolume, volumeID)
	return err
}

const deleteOldFileMetadata = `-- name: DeleteOldFileMetadata :exec
DELETE FROM file_metadata 
WHERE extracted_at < ?
  AND extracted_at IS NOT NULL
`

// Retention queries for cleanup
func (q *Queries) DeleteOldFileMetadata(ctx context.Context, extractedAt sql.NullString) error {
	_, err := q.exec(ctx, q.deleteOldFileMetadataStmt, deleteOldFileMetadata, extractedAt)
	return err
}

const getFileMetadata = `-- name: GetFileMetadata :one
SELECT id, file_id, raw_metadata, extracted_at, extractor_version, extraction_duration_ms, error_message FROM file_metadata WHERE file_id = ?
`

func (q *Queries) GetFileMetadata(ctx context.Context, fileID int64) (FileMetadata, error) {
	row := q.queryRow(ctx, q.getFileMetadataStmt, getFileMetadata, fileID)
	var i FileMetadata
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.RawMetadata,
		&i.ExtractedAt,
		&i.ExtractorVersion,
		&i.ExtractionDurationMs,
		&i.ErrorMessage,
	)
	return i, err
}

const getFileMetadataWithFile = `-- name: GetFileMetadataWithFile :one
SELECT fm.id, fm.file_id, fm.raw_metadata, fm.extracted_at, fm.extractor_version, fm.extraction_duration_ms, fm.error_message, f.volume_id, f.path, f.name, f.size_bytes, f.modified_at
FROM file_metadata fm
JOIN files f ON fm.file_id = f.id
WHERE fm.file_id = ?
`

type GetFileMetadataWithFileRow struct {
	ID                   int64          `json:"id"`
	FileID               int64          `json:"file_id"`
	RawMetadata          string         `json:"raw_metadata"`
	ExtractedAt          sql.NullString `json:"extracted_at"`
	ExtractorVersion     sql.NullString `json:"extractor_version"`
	ExtractionDurationMs sql.NullInt64  `json:"extraction_duration_ms"`
	ErrorMessage         sql.NullString `json:"error_message"`
	VolumeID             string         `json:"volume_id"`
	Path                 string         `json:"path"`
	Name                 string         `json:"name"`
	SizeBytes            int64          `json:"size_bytes"`
	ModifiedAt           sql.NullString `json:"modified_at"`
}

func (q *Queries) GetFileMetadataWithFile(ctx context.Context, fileID int64) (GetFileMetadataWithFileRow, error) {
	row := q.queryRow(ctx, q.getFileMetadataWithFileStmt, getFileMetadataWithFile, fileID)
	var i GetFileMetadataWithFileRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.RawMetadata,
		&i.ExtractedAt,
		&i.ExtractorVersion,
		&i.ExtractionDurationMs,
		&i.ErrorMessage,
		&i.VolumeID,
		&i.Path,
		&i.Name,
		&i.SizeBytes,
		&i.ModifiedAt,
	)
	return i, err
}

const listFileMetadata = `-- name: ListFileMetadata :many
SELECT fm.id, fm.file_id, fm.raw_metadata, fm.extracted_at, fm.extractor_version, fm.extraction_duration_ms, fm.error_message, f.volume_id, f.path, f.name 
FROM file_metadata fm
JOIN files f ON fm.file_id = f.id
WHERE f.volume_id = ?
ORDER BY f.path
LIMIT ? OFFSET ?
`

type ListFileMetadataParams struct {
	VolumeID string `json:"volume_id"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type ListFileMetadataRow struct {
	ID                   int64          `json:"id"`
	FileID               int64          `json:"file_id"`
	RawMetadata          string         `json:"raw_metadata"`
	ExtractedAt          sql.NullString `json:"extracted_at"`
	ExtractorVersion     sql.NullString `json:"extractor_version"`
	ExtractionDurationMs sql.NullInt64  `json:"extraction_duration_ms"`
	ErrorMessage         sql.NullString `json:"error_message"`
	VolumeID             string         `json:"volume_id"`
	Path                 string         `json:"path"`
	Name                 string         `json:"name"`
}

func (q *Queries) ListFileMetadata(ctx context.Context, arg ListFileMetadataParams) ([]ListFileMetadataRow, error) {
	rows, err := q.query(ctx, q.listFileMetadataStmt, listFileMetadata, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFileMetadataRow{}
	for rows.Next() {
		var i ListFileMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.RawMetadata,
			&i.ExtractedAt,
			&i.ExtractorVersion,
			&i.ExtractionDurationMs,
			&i.ErrorMessage,
			&i.VolumeID,
			&i.Path,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :one
UPDATE file_metadata
SET 
    raw_metadata = ?,
    extracted_at = ?,
    extractor_version = ?,
    extraction_duration_ms = ?,
    error_message = ?
WHERE file_id = ?
RETURNING id, file_id, raw_metadata, extracted_at, extractor_version, extraction_duration_ms, error_message
`

type UpdateFileMetadataParams struct {
	RawMetadata          string         `json:"raw_metadata"`
	ExtractedAt          sql.NullString `json:"extracted_at"`
	ExtractorVersion     sql.NullString `json:"extractor_version"`
	ExtractionDurationMs sql.NullInt64  `json:"extraction_duration_ms"`
	ErrorMessage         sql.NullString `json:"error_message"`
	FileID               int64          `json:"file_id"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (FileMetadata, error) {
	row := q.queryRow(ctx, q.updateFileMetadataStmt, updateFileMetadata,
		arg.RawMetadata,
		arg.ExtractedAt,
		arg.ExtractorVersion,
		arg.ExtractionDurationMs,
		arg.ErrorMessage,
		arg.FileID,
	)
	var i FileMetadata
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.RawMetadata,
		&i.ExtractedAt,
		&i.ExtractorVersion,
		&i.ExtractionDurationMs,
		&i.ErrorMessage,
	)
	return i, err
}
