// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scans.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelScanJob = `-- name: CancelScanJob :exec
UPDATE scan_jobs
SET 
    status = 'cancelled',
    completed_at = datetime('now'),
    updated_at = datetime('now')
WHERE scan_id = ?1
`

func (q *Queries) CancelScanJob(ctx context.Context, scanID string) error {
	_, err := q.exec(ctx, q.cancelScanJobStmt, cancelScanJob, scanID)
	return err
}

const completeScanJob = `-- name: CompleteScanJob :exec
UPDATE scan_jobs
SET 
    status = 'completed',
    completed_at = datetime('now'),
    updated_at = datetime('now')
WHERE scan_id = ?1
`

func (q *Queries) CompleteScanJob(ctx context.Context, scanID string) error {
	_, err := q.exec(ctx, q.completeScanJobStmt, completeScanJob, scanID)
	return err
}

const countScanJobsByStatus = `-- name: CountScanJobsByStatus :one
SELECT COUNT(*) FROM scan_jobs WHERE status = ?
`

func (q *Queries) CountScanJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.queryRow(ctx, q.countScanJobsByStatusStmt, countScanJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScanJob = `-- name: CreateScanJob :one

INSERT INTO scan_jobs (
    scan_id, volume_id, status, started_at
) VALUES (
    ?, ?, ?, ?
) RETURNING scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at
`

type CreateScanJobParams struct {
	ScanID    string         `json:"scan_id"`
	VolumeID  sql.NullString `json:"volume_id"`
	Status    string         `json:"status"`
	StartedAt sql.NullString `json:"started_at"`
}

// Scan job management queries for SQLite
func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJobs, error) {
	row := q.queryRow(ctx, q.createScanJobStmt, createScanJob,
		arg.ScanID,
		arg.VolumeID,
		arg.Status,
		arg.StartedAt,
	)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldScanJobs = `-- name: DeleteOldScanJobs :exec
DELETE FROM scan_jobs
WHERE completed_at < ?
AND status IN ('completed', 'failed', 'cancelled')
`

func (q *Queries) DeleteOldScanJobs(ctx context.Context, completedAt sql.NullString) error {
	_, err := q.exec(ctx, q.deleteOldScanJobsStmt, deleteOldScanJobs, completedAt)
	return err
}

const failScanJob = `-- name: FailScanJob :exec
UPDATE scan_jobs
SET 
    status = 'failed',
    error_message = ?2,
    completed_at = datetime('now'),
    updated_at = datetime('now')
WHERE scan_id = ?1
`

type FailScanJobParams struct {
	ScanID       string         `json:"scan_id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) FailScanJob(ctx context.Context, arg FailScanJobParams) error {
	_, err := q.exec(ctx, q.failScanJobStmt, failScanJob, arg.ScanID, arg.ErrorMessage)
	return err
}

const getActiveScanJobs = `-- name: GetActiveScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at FROM scan_jobs
WHERE status IN ('pending', 'running')
ORDER BY started_at ASC
`

func (q *Queries) GetActiveScanJobs(ctx context.Context) ([]ScanJobs, error) {
	rows, err := q.query(ctx, q.getActiveScanJobsStmt, getActiveScanJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedScanJobs = `-- name: GetCompletedScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at FROM scan_jobs
WHERE status = 'completed'
AND completed_at >= ?
ORDER BY completed_at DESC
LIMIT ?
`

type GetCompletedScanJobsParams struct {
	CompletedAt sql.NullString `json:"completed_at"`
	Limit       int64          `json:"limit"`
}

func (q *Queries) GetCompletedScanJobs(ctx context.Context, arg GetCompletedScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.query(ctx, q.getCompletedScanJobsStmt, getCompletedScanJobs, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanJobByScanID = `-- name: GetScanJobByScanID :one
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at FROM scan_jobs WHERE scan_id = ?
`

func (q *Queries) GetScanJobByScanID(ctx context.Context, scanID string) (ScanJobs, error) {
	row := q.queryRow(ctx, q.getScanJobByScanIDStmt, getScanJobByScanID, scanID)
	var i ScanJobs
	err := row.Scan(
		&i.ScanID,
		&i.VolumeID,
		&i.Status,
		&i.TotalFiles,
		&i.ScannedFiles,
		&i.FailedFiles,
		&i.TotalBytes,
		&i.ScannedBytes,
		&i.ScanRateFilesPerSec,
		&i.ScanRateMbPerSec,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PausedAt,
		&i.PauseReason,
		&i.DurationSeconds,
		&i.TriggeredBy,
		&i.ScanOptions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScanJobs = `-- name: ListScanJobs :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at FROM scan_jobs
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListScanJobsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListScanJobs(ctx context.Context, arg ListScanJobsParams) ([]ScanJobs, error) {
	rows, err := q.query(ctx, q.listScanJobsStmt, listScanJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByStatus = `-- name: ListScanJobsByStatus :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at FROM scan_jobs
WHERE status = ?
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListScanJobsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListScanJobsByStatus(ctx context.Context, arg ListScanJobsByStatusParams) ([]ScanJobs, error) {
	rows, err := q.query(ctx, q.listScanJobsByStatusStmt, listScanJobsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByVolume = `-- name: ListScanJobsByVolume :many
SELECT scan_id, volume_id, status, total_files, scanned_files, failed_files, total_bytes, scanned_bytes, scan_rate_files_per_sec, scan_rate_mb_per_sec, error_message, error_details, started_at, completed_at, paused_at, pause_reason, duration_seconds, triggered_by, scan_options, created_at, updated_at FROM scan_jobs
WHERE volume_id = ?
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListScanJobsByVolumeParams struct {
	VolumeID sql.NullString `json:"volume_id"`
	Limit    int64          `json:"limit"`
	Offset   int64          `json:"offset"`
}

func (q *Queries) ListScanJobsByVolume(ctx context.Context, arg ListScanJobsByVolumeParams) ([]ScanJobs, error) {
	rows, err := q.query(ctx, q.listScanJobsByVolumeStmt, listScanJobsByVolume, arg.VolumeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanJobs{}
	for rows.Next() {
		var i ScanJobs
		if err := rows.Scan(
			&i.ScanID,
			&i.VolumeID,
			&i.Status,
			&i.TotalFiles,
			&i.ScannedFiles,
			&i.FailedFiles,
			&i.TotalBytes,
			&i.ScannedBytes,
			&i.ScanRateFilesPerSec,
			&i.ScanRateMbPerSec,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.PauseReason,
			&i.DurationSeconds,
			&i.TriggeredBy,
			&i.ScanOptions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInFlightJobsAsPaused = `-- name: MarkInFlightJobsAsPaused :many
UPDATE scan_jobs
SET 
    status = 'paused',
    error_message = ?,
    updated_at = datetime('now')
WHERE status IN ('running', 'pending')
RETURNING scan_id
`

func (q *Queries) MarkInFlightJobsAsPaused(ctx context.Context, errorMessage sql.NullString) ([]string, error) {
	rows, err := q.query(ctx, q.markInFlightJobsAsPausedStmt, markInFlightJobsAsPaused, errorMessage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleScanJobsAsFailed = `-- name: MarkStaleScanJobsAsFailed :many
UPDATE scan_jobs
SET 
    status = 'failed',
    error_message = 'Scan job marked as stale after timeout',
    completed_at = datetime('now'),
    updated_at = datetime('now')
WHERE status = 'running'
  AND started_at < datetime('now', '-' || ? || ' seconds')
  AND started_at IS NOT NULL
RETURNING scan_id
`

func (q *Queries) MarkStaleScanJobsAsFailed(ctx context.Context, dollar_1 sql.NullString) ([]string, error) {
	rows, err := q.query(ctx, q.markStaleScanJobsAsFailedStmt, markStaleScanJobsAsFailed, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scan_id string
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanJobProgress = `-- name: UpdateScanJobProgress :exec
UPDATE scan_jobs
SET 
    scanned_files = ?2,
    scanned_bytes = ?3,
    updated_at = datetime('now')
WHERE scan_id = ?1
`

type UpdateScanJobProgressParams struct {
	ScanID       string        `json:"scan_id"`
	ScannedFiles sql.NullInt64 `json:"scanned_files"`
	ScannedBytes sql.NullInt64 `json:"scanned_bytes"`
}

func (q *Queries) UpdateScanJobProgress(ctx context.Context, arg UpdateScanJobProgressParams) error {
	_, err := q.exec(ctx, q.updateScanJobProgressStmt, updateScanJobProgress, arg.ScanID, arg.ScannedFiles, arg.ScannedBytes)
	return err
}

const updateScanJobStatus = `-- name: UpdateScanJobStatus :exec
UPDATE scan_jobs
SET 
    status = ?1,
    error_message = CASE WHEN ?1 = 'failed' THEN ?2 ELSE error_message END,
    completed_at = CASE WHEN ?1 IN ('completed', 'failed', 'cancelled') THEN datetime('now') ELSE completed_at END,
    updated_at = datetime('now')
WHERE scan_id = ?3
`

type UpdateScanJobStatusParams struct {
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	ScanID       string         `json:"scan_id"`
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) error {
	_, err := q.exec(ctx, q.updateScanJobStatusStmt, updateScanJobStatus, arg.Status, arg.ErrorMessage, arg.ScanID)
	return err
}
