// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tracking_rules.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMountTrackingAssignment = `-- name: CreateMountTrackingAssignment :one

INSERT INTO mount_tracking_assignments (
    mount_catalog_id, rule_id, evaluation_id, action, is_active,
    matched_conditions, rule_priority, rule_name, expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, mount_catalog_id, rule_id, evaluation_id, "action", is_active, matched_conditions, rule_priority, rule_name, assigned_at, expires_at, created_at, updated_at
`

type CreateMountTrackingAssignmentParams struct {
	MountCatalogID    sql.NullInt64  `json:"mount_catalog_id"`
	RuleID            sql.NullInt64  `json:"rule_id"`
	EvaluationID      sql.NullInt64  `json:"evaluation_id"`
	Action            string         `json:"action"`
	IsActive          int64          `json:"is_active"`
	MatchedConditions sql.NullString `json:"matched_conditions"`
	RulePriority      sql.NullInt64  `json:"rule_priority"`
	RuleName          sql.NullString `json:"rule_name"`
	ExpiresAt         sql.NullString `json:"expires_at"`
}

// =============================================================================
// MOUNT TRACKING ASSIGNMENTS
// =============================================================================
func (q *Queries) CreateMountTrackingAssignment(ctx context.Context, arg CreateMountTrackingAssignmentParams) (MountTrackingAssignments, error) {
	row := q.queryRow(ctx, q.createMountTrackingAssignmentStmt, createMountTrackingAssignment,
		arg.MountCatalogID,
		arg.RuleID,
		arg.EvaluationID,
		arg.Action,
		arg.IsActive,
		arg.MatchedConditions,
		arg.RulePriority,
		arg.RuleName,
		arg.ExpiresAt,
	)
	var i MountTrackingAssignments
	err := row.Scan(
		&i.ID,
		&i.MountCatalogID,
		&i.RuleID,
		&i.EvaluationID,
		&i.Action,
		&i.IsActive,
		&i.MatchedConditions,
		&i.RulePriority,
		&i.RuleName,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackingRule = `-- name: CreateTrackingRule :one


INSERT INTO tracking_rules (
    name, description, action, priority, is_enabled, 
    conditions, created_by
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, description, "action", priority, is_enabled, conditions, match_count, last_matched_at, last_evaluation_at, created_by, created_at, updated_at
`

type CreateTrackingRuleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Action      string         `json:"action"`
	Priority    int64          `json:"priority"`
	IsEnabled   int64          `json:"is_enabled"`
	Conditions  string         `json:"conditions"`
	CreatedBy   sql.NullString `json:"created_by"`
}

// Tracking Rules Engine Queries (SQLite version)
// SQLC queries for tracking rules operations
// =============================================================================
// TRACKING RULES
// =============================================================================
func (q *Queries) CreateTrackingRule(ctx context.Context, arg CreateTrackingRuleParams) (TrackingRules, error) {
	row := q.queryRow(ctx, q.createTrackingRuleStmt, createTrackingRule,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.Priority,
		arg.IsEnabled,
		arg.Conditions,
		arg.CreatedBy,
	)
	var i TrackingRules
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.Priority,
		&i.IsEnabled,
		&i.Conditions,
		&i.MatchCount,
		&i.LastMatchedAt,
		&i.LastEvaluationAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackingRuleCondition = `-- name: CreateTrackingRuleCondition :one

INSERT INTO tracking_rule_conditions (
    rule_id, field_name, operator, value, values, 
    is_case_sensitive, description
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, rule_id, field_name, operator, value, "values", is_case_sensitive, description, match_count, last_matched_at, created_at, updated_at
`

type CreateTrackingRuleConditionParams struct {
	RuleID          sql.NullInt64  `json:"rule_id"`
	FieldName       string         `json:"field_name"`
	Operator        string         `json:"operator"`
	Value           sql.NullString `json:"value"`
	Values          sql.NullString `json:"values"`
	IsCaseSensitive int64          `json:"is_case_sensitive"`
	Description     sql.NullString `json:"description"`
}

// =============================================================================
// RULE CONDITIONS
// =============================================================================
func (q *Queries) CreateTrackingRuleCondition(ctx context.Context, arg CreateTrackingRuleConditionParams) (TrackingRuleConditions, error) {
	row := q.queryRow(ctx, q.createTrackingRuleConditionStmt, createTrackingRuleCondition,
		arg.RuleID,
		arg.FieldName,
		arg.Operator,
		arg.Value,
		arg.Values,
		arg.IsCaseSensitive,
		arg.Description,
	)
	var i TrackingRuleConditions
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.FieldName,
		&i.Operator,
		&i.Value,
		&i.Values,
		&i.IsCaseSensitive,
		&i.Description,
		&i.MatchCount,
		&i.LastMatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackingRuleEvaluation = `-- name: CreateTrackingRuleEvaluation :one

INSERT INTO tracking_rule_evaluations (
    rule_id, evaluation_type, triggered_by, status,
    mounts_evaluated, mounts_matched, mounts_included, mounts_excluded,
    execution_time_ms, error_message, error_details, started_at, completed_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, rule_id, evaluation_type, triggered_by, status, mounts_evaluated, mounts_matched, mounts_included, mounts_excluded, execution_time_ms, error_message, error_details, started_at, completed_at, created_at
`

type CreateTrackingRuleEvaluationParams struct {
	RuleID          sql.NullInt64  `json:"rule_id"`
	EvaluationType  string         `json:"evaluation_type"`
	TriggeredBy     sql.NullString `json:"triggered_by"`
	Status          string         `json:"status"`
	MountsEvaluated int64          `json:"mounts_evaluated"`
	MountsMatched   int64          `json:"mounts_matched"`
	MountsIncluded  int64          `json:"mounts_included"`
	MountsExcluded  int64          `json:"mounts_excluded"`
	ExecutionTimeMs sql.NullInt64  `json:"execution_time_ms"`
	ErrorMessage    sql.NullString `json:"error_message"`
	ErrorDetails    sql.NullString `json:"error_details"`
	StartedAt       string         `json:"started_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
}

// =============================================================================
// RULE EVALUATIONS
// =============================================================================
func (q *Queries) CreateTrackingRuleEvaluation(ctx context.Context, arg CreateTrackingRuleEvaluationParams) (TrackingRuleEvaluations, error) {
	row := q.queryRow(ctx, q.createTrackingRuleEvaluationStmt, createTrackingRuleEvaluation,
		arg.RuleID,
		arg.EvaluationType,
		arg.TriggeredBy,
		arg.Status,
		arg.MountsEvaluated,
		arg.MountsMatched,
		arg.MountsIncluded,
		arg.MountsExcluded,
		arg.ExecutionTimeMs,
		arg.ErrorMessage,
		arg.ErrorDetails,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i TrackingRuleEvaluations
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.EvaluationType,
		&i.TriggeredBy,
		&i.Status,
		&i.MountsEvaluated,
		&i.MountsMatched,
		&i.MountsIncluded,
		&i.MountsExcluded,
		&i.ExecutionTimeMs,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTrackingRuleTemplate = `-- name: CreateTrackingRuleTemplate :one
INSERT INTO tracking_rule_templates (
    name, description, category, template_data, is_builtin, tags
) VALUES (
    ?, ?, ?, ?, ?, ?
) RETURNING id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at
`

type CreateTrackingRuleTemplateParams struct {
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	Category     string         `json:"category"`
	TemplateData string         `json:"template_data"`
	IsBuiltin    int64          `json:"is_builtin"`
	Tags         sql.NullString `json:"tags"`
}

func (q *Queries) CreateTrackingRuleTemplate(ctx context.Context, arg CreateTrackingRuleTemplateParams) (TrackingRuleTemplates, error) {
	row := q.queryRow(ctx, q.createTrackingRuleTemplateStmt, createTrackingRuleTemplate,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.TemplateData,
		arg.IsBuiltin,
		arg.Tags,
	)
	var i TrackingRuleTemplates
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.TemplateData,
		&i.UsageCount,
		&i.LastUsedAt,
		&i.IsBuiltin,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateMountAssignment = `-- name: DeactivateMountAssignment :exec
UPDATE mount_tracking_assignments
SET is_active = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE mount_catalog_id = ? AND is_active = 1
`

func (q *Queries) DeactivateMountAssignment(ctx context.Context, mountCatalogID sql.NullInt64) error {
	_, err := q.exec(ctx, q.deactivateMountAssignmentStmt, deactivateMountAssignment, mountCatalogID)
	return err
}

const deleteRuleConditions = `-- name: DeleteRuleConditions :exec
DELETE FROM tracking_rule_conditions
WHERE rule_id = ?
`

func (q *Queries) DeleteRuleConditions(ctx context.Context, ruleID sql.NullInt64) error {
	_, err := q.exec(ctx, q.deleteRuleConditionsStmt, deleteRuleConditions, ruleID)
	return err
}

const deleteTrackingRule = `-- name: DeleteTrackingRule :exec
DELETE FROM tracking_rules
WHERE id = ?
`

func (q *Queries) DeleteTrackingRule(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteTrackingRuleStmt, deleteTrackingRule, id)
	return err
}

const deleteTrackingRuleTemplate = `-- name: DeleteTrackingRuleTemplate :exec
DELETE FROM tracking_rule_templates
WHERE id = ? AND is_builtin = 0
`

func (q *Queries) DeleteTrackingRuleTemplate(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteTrackingRuleTemplateStmt, deleteTrackingRuleTemplate, id)
	return err
}

const expireOldAssignments = `-- name: ExpireOldAssignments :exec
UPDATE mount_tracking_assignments
SET is_active = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE expires_at < CURRENT_TIMESTAMP AND is_active = 1
`

func (q *Queries) ExpireOldAssignments(ctx context.Context) error {
	_, err := q.exec(ctx, q.expireOldAssignmentsStmt, expireOldAssignments)
	return err
}

const getActiveMountAssignment = `-- name: GetActiveMountAssignment :one
SELECT id, mount_catalog_id, rule_id, evaluation_id, "action", is_active, matched_conditions, rule_priority, rule_name, assigned_at, expires_at, created_at, updated_at FROM mount_tracking_assignments
WHERE mount_catalog_id = ? AND is_active = 1
`

func (q *Queries) GetActiveMountAssignment(ctx context.Context, mountCatalogID sql.NullInt64) (MountTrackingAssignments, error) {
	row := q.queryRow(ctx, q.getActiveMountAssignmentStmt, getActiveMountAssignment, mountCatalogID)
	var i MountTrackingAssignments
	err := row.Scan(
		&i.ID,
		&i.MountCatalogID,
		&i.RuleID,
		&i.EvaluationID,
		&i.Action,
		&i.IsActive,
		&i.MatchedConditions,
		&i.RulePriority,
		&i.RuleName,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRuleEvaluation = `-- name: GetLatestRuleEvaluation :one
SELECT id, rule_id, evaluation_type, triggered_by, status, mounts_evaluated, mounts_matched, mounts_included, mounts_excluded, execution_time_ms, error_message, error_details, started_at, completed_at, created_at FROM tracking_rule_evaluations
WHERE rule_id = ?
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRuleEvaluation(ctx context.Context, ruleID sql.NullInt64) (TrackingRuleEvaluations, error) {
	row := q.queryRow(ctx, q.getLatestRuleEvaluationStmt, getLatestRuleEvaluation, ruleID)
	var i TrackingRuleEvaluations
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.EvaluationType,
		&i.TriggeredBy,
		&i.Status,
		&i.MountsEvaluated,
		&i.MountsMatched,
		&i.MountsIncluded,
		&i.MountsExcluded,
		&i.ExecutionTimeMs,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMountTrackingAssignment = `-- name: GetMountTrackingAssignment :one
SELECT id, mount_catalog_id, rule_id, evaluation_id, "action", is_active, matched_conditions, rule_priority, rule_name, assigned_at, expires_at, created_at, updated_at FROM mount_tracking_assignments
WHERE id = ?
`

func (q *Queries) GetMountTrackingAssignment(ctx context.Context, id int64) (MountTrackingAssignments, error) {
	row := q.queryRow(ctx, q.getMountTrackingAssignmentStmt, getMountTrackingAssignment, id)
	var i MountTrackingAssignments
	err := row.Scan(
		&i.ID,
		&i.MountCatalogID,
		&i.RuleID,
		&i.EvaluationID,
		&i.Action,
		&i.IsActive,
		&i.MatchedConditions,
		&i.RulePriority,
		&i.RuleName,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleConditions = `-- name: GetRuleConditions :many
SELECT id, rule_id, field_name, operator, value, "values", is_case_sensitive, description, match_count, last_matched_at, created_at, updated_at FROM tracking_rule_conditions
WHERE rule_id = ?
ORDER BY id
`

func (q *Queries) GetRuleConditions(ctx context.Context, ruleID sql.NullInt64) ([]TrackingRuleConditions, error) {
	rows, err := q.query(ctx, q.getRuleConditionsStmt, getRuleConditions, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRuleConditions{}
	for rows.Next() {
		var i TrackingRuleConditions
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.FieldName,
			&i.Operator,
			&i.Value,
			&i.Values,
			&i.IsCaseSensitive,
			&i.Description,
			&i.MatchCount,
			&i.LastMatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackingRule = `-- name: GetTrackingRule :one
SELECT id, name, description, "action", priority, is_enabled, conditions, match_count, last_matched_at, last_evaluation_at, created_by, created_at, updated_at FROM tracking_rules
WHERE id = ?
`

func (q *Queries) GetTrackingRule(ctx context.Context, id int64) (TrackingRules, error) {
	row := q.queryRow(ctx, q.getTrackingRuleStmt, getTrackingRule, id)
	var i TrackingRules
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.Priority,
		&i.IsEnabled,
		&i.Conditions,
		&i.MatchCount,
		&i.LastMatchedAt,
		&i.LastEvaluationAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackingRuleByName = `-- name: GetTrackingRuleByName :one
SELECT id, name, description, "action", priority, is_enabled, conditions, match_count, last_matched_at, last_evaluation_at, created_by, created_at, updated_at FROM tracking_rules
WHERE name = ?
`

func (q *Queries) GetTrackingRuleByName(ctx context.Context, name string) (TrackingRules, error) {
	row := q.queryRow(ctx, q.getTrackingRuleByNameStmt, getTrackingRuleByName, name)
	var i TrackingRules
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.Priority,
		&i.IsEnabled,
		&i.Conditions,
		&i.MatchCount,
		&i.LastMatchedAt,
		&i.LastEvaluationAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackingRuleEvaluation = `-- name: GetTrackingRuleEvaluation :one
SELECT id, rule_id, evaluation_type, triggered_by, status, mounts_evaluated, mounts_matched, mounts_included, mounts_excluded, execution_time_ms, error_message, error_details, started_at, completed_at, created_at FROM tracking_rule_evaluations
WHERE id = ?
`

func (q *Queries) GetTrackingRuleEvaluation(ctx context.Context, id int64) (TrackingRuleEvaluations, error) {
	row := q.queryRow(ctx, q.getTrackingRuleEvaluationStmt, getTrackingRuleEvaluation, id)
	var i TrackingRuleEvaluations
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.EvaluationType,
		&i.TriggeredBy,
		&i.Status,
		&i.MountsEvaluated,
		&i.MountsMatched,
		&i.MountsIncluded,
		&i.MountsExcluded,
		&i.ExecutionTimeMs,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTrackingRuleTemplate = `-- name: GetTrackingRuleTemplate :one

SELECT id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at FROM tracking_rule_templates
WHERE id = ?
`

// =============================================================================
// RULE TEMPLATES
// =============================================================================
func (q *Queries) GetTrackingRuleTemplate(ctx context.Context, id int64) (TrackingRuleTemplates, error) {
	row := q.queryRow(ctx, q.getTrackingRuleTemplateStmt, getTrackingRuleTemplate, id)
	var i TrackingRuleTemplates
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.TemplateData,
		&i.UsageCount,
		&i.LastUsedAt,
		&i.IsBuiltin,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrackingRuleTemplateByName = `-- name: GetTrackingRuleTemplateByName :one
SELECT id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at FROM tracking_rule_templates
WHERE name = ?
`

func (q *Queries) GetTrackingRuleTemplateByName(ctx context.Context, name string) (TrackingRuleTemplates, error) {
	row := q.queryRow(ctx, q.getTrackingRuleTemplateByNameStmt, getTrackingRuleTemplateByName, name)
	var i TrackingRuleTemplates
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.TemplateData,
		&i.UsageCount,
		&i.LastUsedAt,
		&i.IsBuiltin,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAssignments = `-- name: ListActiveAssignments :many
SELECT id, mount_catalog_id, rule_id, evaluation_id, "action", is_active, matched_conditions, rule_priority, rule_name, assigned_at, expires_at, created_at, updated_at FROM mount_tracking_assignments
WHERE is_active = 1
ORDER BY assigned_at DESC
`

func (q *Queries) ListActiveAssignments(ctx context.Context) ([]MountTrackingAssignments, error) {
	rows, err := q.query(ctx, q.listActiveAssignmentsStmt, listActiveAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MountTrackingAssignments{}
	for rows.Next() {
		var i MountTrackingAssignments
		if err := rows.Scan(
			&i.ID,
			&i.MountCatalogID,
			&i.RuleID,
			&i.EvaluationID,
			&i.Action,
			&i.IsActive,
			&i.MatchedConditions,
			&i.RulePriority,
			&i.RuleName,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuiltinTemplates = `-- name: ListBuiltinTemplates :many
SELECT id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at FROM tracking_rule_templates
WHERE is_builtin = 1
ORDER BY category, name
`

func (q *Queries) ListBuiltinTemplates(ctx context.Context) ([]TrackingRuleTemplates, error) {
	rows, err := q.query(ctx, q.listBuiltinTemplatesStmt, listBuiltinTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRuleTemplates{}
	for rows.Next() {
		var i TrackingRuleTemplates
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.TemplateData,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.IsBuiltin,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTrackingRules = `-- name: ListEnabledTrackingRules :many
SELECT id, name, description, "action", priority, is_enabled, conditions, match_count, last_matched_at, last_evaluation_at, created_by, created_at, updated_at FROM tracking_rules
WHERE is_enabled = 1
ORDER BY priority ASC, id ASC
`

func (q *Queries) ListEnabledTrackingRules(ctx context.Context) ([]TrackingRules, error) {
	rows, err := q.query(ctx, q.listEnabledTrackingRulesStmt, listEnabledTrackingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRules{}
	for rows.Next() {
		var i TrackingRules
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Action,
			&i.Priority,
			&i.IsEnabled,
			&i.Conditions,
			&i.MatchCount,
			&i.LastMatchedAt,
			&i.LastEvaluationAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMountAssignments = `-- name: ListMountAssignments :many
SELECT id, mount_catalog_id, rule_id, evaluation_id, "action", is_active, matched_conditions, rule_priority, rule_name, assigned_at, expires_at, created_at, updated_at FROM mount_tracking_assignments
WHERE mount_catalog_id = ?
ORDER BY assigned_at DESC
LIMIT ? OFFSET ?
`

type ListMountAssignmentsParams struct {
	MountCatalogID sql.NullInt64 `json:"mount_catalog_id"`
	Limit          int64         `json:"limit"`
	Offset         int64         `json:"offset"`
}

func (q *Queries) ListMountAssignments(ctx context.Context, arg ListMountAssignmentsParams) ([]MountTrackingAssignments, error) {
	rows, err := q.query(ctx, q.listMountAssignmentsStmt, listMountAssignments, arg.MountCatalogID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MountTrackingAssignments{}
	for rows.Next() {
		var i MountTrackingAssignments
		if err := rows.Scan(
			&i.ID,
			&i.MountCatalogID,
			&i.RuleID,
			&i.EvaluationID,
			&i.Action,
			&i.IsActive,
			&i.MatchedConditions,
			&i.RulePriority,
			&i.RuleName,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleEvaluations = `-- name: ListRuleEvaluations :many
SELECT id, rule_id, evaluation_type, triggered_by, status, mounts_evaluated, mounts_matched, mounts_included, mounts_excluded, execution_time_ms, error_message, error_details, started_at, completed_at, created_at FROM tracking_rule_evaluations
WHERE rule_id = ?
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListRuleEvaluationsParams struct {
	RuleID sql.NullInt64 `json:"rule_id"`
	Limit  int64         `json:"limit"`
	Offset int64         `json:"offset"`
}

func (q *Queries) ListRuleEvaluations(ctx context.Context, arg ListRuleEvaluationsParams) ([]TrackingRuleEvaluations, error) {
	rows, err := q.query(ctx, q.listRuleEvaluationsStmt, listRuleEvaluations, arg.RuleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRuleEvaluations{}
	for rows.Next() {
		var i TrackingRuleEvaluations
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.EvaluationType,
			&i.TriggeredBy,
			&i.Status,
			&i.MountsEvaluated,
			&i.MountsMatched,
			&i.MountsIncluded,
			&i.MountsExcluded,
			&i.ExecutionTimeMs,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByCategory = `-- name: ListTemplatesByCategory :many
SELECT id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at FROM tracking_rule_templates
WHERE category = ?
ORDER BY name
`

func (q *Queries) ListTemplatesByCategory(ctx context.Context, category string) ([]TrackingRuleTemplates, error) {
	rows, err := q.query(ctx, q.listTemplatesByCategoryStmt, listTemplatesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRuleTemplates{}
	for rows.Next() {
		var i TrackingRuleTemplates
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.TemplateData,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.IsBuiltin,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingRuleTemplates = `-- name: ListTrackingRuleTemplates :many
SELECT id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at FROM tracking_rule_templates
ORDER BY category, name
LIMIT ? OFFSET ?
`

type ListTrackingRuleTemplatesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTrackingRuleTemplates(ctx context.Context, arg ListTrackingRuleTemplatesParams) ([]TrackingRuleTemplates, error) {
	rows, err := q.query(ctx, q.listTrackingRuleTemplatesStmt, listTrackingRuleTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRuleTemplates{}
	for rows.Next() {
		var i TrackingRuleTemplates
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.TemplateData,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.IsBuiltin,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingRules = `-- name: ListTrackingRules :many
SELECT id, name, description, "action", priority, is_enabled, conditions, match_count, last_matched_at, last_evaluation_at, created_by, created_at, updated_at FROM tracking_rules
ORDER BY priority ASC, id ASC
LIMIT ? OFFSET ?
`

type ListTrackingRulesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTrackingRules(ctx context.Context, arg ListTrackingRulesParams) ([]TrackingRules, error) {
	rows, err := q.query(ctx, q.listTrackingRulesStmt, listTrackingRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingRules{}
	for rows.Next() {
		var i TrackingRules
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Action,
			&i.Priority,
			&i.IsEnabled,
			&i.Conditions,
			&i.MatchCount,
			&i.LastMatchedAt,
			&i.LastEvaluationAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConditionStats = `-- name: UpdateConditionStats :exec
UPDATE tracking_rule_conditions
SET match_count = match_count + 1,
    last_matched_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateConditionStats(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.updateConditionStatsStmt, updateConditionStats, id)
	return err
}

const updateTemplateUsage = `-- name: UpdateTemplateUsage :exec
UPDATE tracking_rule_templates
SET usage_count = usage_count + 1,
    last_used_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateTemplateUsage(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.updateTemplateUsageStmt, updateTemplateUsage, id)
	return err
}

const updateTrackingRule = `-- name: UpdateTrackingRule :one
UPDATE tracking_rules
SET name = ?,
    description = ?,
    action = ?,
    priority = ?,
    is_enabled = ?,
    conditions = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, "action", priority, is_enabled, conditions, match_count, last_matched_at, last_evaluation_at, created_by, created_at, updated_at
`

type UpdateTrackingRuleParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Action      string         `json:"action"`
	Priority    int64          `json:"priority"`
	IsEnabled   int64          `json:"is_enabled"`
	Conditions  string         `json:"conditions"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTrackingRule(ctx context.Context, arg UpdateTrackingRuleParams) (TrackingRules, error) {
	row := q.queryRow(ctx, q.updateTrackingRuleStmt, updateTrackingRule,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.Priority,
		arg.IsEnabled,
		arg.Conditions,
		arg.ID,
	)
	var i TrackingRules
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.Priority,
		&i.IsEnabled,
		&i.Conditions,
		&i.MatchCount,
		&i.LastMatchedAt,
		&i.LastEvaluationAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrackingRuleStats = `-- name: UpdateTrackingRuleStats :exec
UPDATE tracking_rules
SET match_count = match_count + ?,
    last_matched_at = CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE last_matched_at END,
    last_evaluation_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTrackingRuleStatsParams struct {
	MatchCount    int64          `json:"match_count"`
	LastMatchedAt sql.NullString `json:"last_matched_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateTrackingRuleStats(ctx context.Context, arg UpdateTrackingRuleStatsParams) error {
	_, err := q.exec(ctx, q.updateTrackingRuleStatsStmt, updateTrackingRuleStats, arg.MatchCount, arg.LastMatchedAt, arg.ID)
	return err
}

const updateTrackingRuleTemplate = `-- name: UpdateTrackingRuleTemplate :one
UPDATE tracking_rule_templates
SET description = ?,
    category = ?,
    template_data = ?,
    tags = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, category, template_data, usage_count, last_used_at, is_builtin, tags, created_at, updated_at
`

type UpdateTrackingRuleTemplateParams struct {
	Description  string         `json:"description"`
	Category     string         `json:"category"`
	TemplateData string         `json:"template_data"`
	Tags         sql.NullString `json:"tags"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateTrackingRuleTemplate(ctx context.Context, arg UpdateTrackingRuleTemplateParams) (TrackingRuleTemplates, error) {
	row := q.queryRow(ctx, q.updateTrackingRuleTemplateStmt, updateTrackingRuleTemplate,
		arg.Description,
		arg.Category,
		arg.TemplateData,
		arg.Tags,
		arg.ID,
	)
	var i TrackingRuleTemplates
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.TemplateData,
		&i.UsageCount,
		&i.LastUsedAt,
		&i.IsBuiltin,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
