-- Seed data for a fresh dev database. Idempotent (ON CONFLICT DO NOTHING),
-- safe to run against an already-seeded database.
--
-- Matches the schema as of migration 000016 (add_volume_tracking). If this
-- starts failing with "column does not exist", the schema has moved on and
-- this file needs the same treatment.

-- Organization
INSERT INTO organizations (id, name, display_name)
VALUES (1, 'default', 'Default Organization')
ON CONFLICT (id) DO NOTHING;

-- Demo user: demouser / NewPassword123 (matches the hint shown on the
-- login page). Hash generated by the real backend's bcrypt.DefaultCost,
-- not hand-rolled, so it's guaranteed compatible with the login handler.
INSERT INTO users (organization_id, username, email, password_hash, role, is_active)
VALUES (
    1,
    'demouser',
    'demouser@volumeviz.local',
    '$2a$10$t1V3E7xfEo5ZJnNP8Q.3wehFdBWV1qBAwA28ewkQrIIK2Xjs6AXN.',
    'admin',
    true
)
ON CONFLICT (username, organization_id) DO NOTHING;

-- Sample volumes so the dashboard/volumes list isn't empty on first login.
INSERT INTO volumes (
    volume_id, display_name, mount_point, is_active, total_size_bytes,
    used_size_bytes, free_size_bytes, filesystem_type, driver, scope,
    is_tracked, organization_id
) VALUES
    (
        'demo-app-data', 'demo-app-data',
        '/var/lib/docker/volumes/demo-app-data/_data',
        true, 2147483648, 429496730, 1717986918, 'ext4', 'local', 'local',
        true, 1
    ),
    (
        'demo-db-data', 'demo-db-data',
        '/var/lib/docker/volumes/demo-db-data/_data',
        true, 5368709120, 3221225472, 2147483648, 'ext4', 'local', 'local',
        true, 1
    )
ON CONFLICT (volume_id) DO NOTHING;
