name: Backend CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md" 
      - "docs/**"
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"

jobs:
  go:
    name: Go Build, Test & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Download Go modules
        run: go mod download

      - name: Verify Go modules
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --verbose

      - name: Run tests with race detection and coverage
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out -v ./...

      - name: Enforce coverage threshold (60%)
        run: |
          echo "📊 Analyzing test coverage..."
          pct=$(go tool cover -func=coverage.out | awk '/total:/ {print substr($3, 1, length($3)-1)}')
          echo "Total coverage: ${pct}%"
          echo ""
          echo "Coverage by package:"
          go tool cover -func=coverage.out | grep -v "total:" | sort -k3 -nr
          echo ""
          awk -v p="$pct" 'BEGIN { 
            if (p+0 < 60) { 
              print "❌ Coverage below minimum threshold"
              print "   Required: ≥60%"
              print "   Actual:   " p "%"
              print "   Gap:      " (60 - p) "%"
              print ""
              print "Please add tests to improve coverage before merging."
              print "Focus on packages with lower coverage shown above."
              exit 1 
            } else {
              print "✅ Coverage meets threshold: " p "% (≥60%)"
              if (p+0 >= 80) {
                print "🌟 Excellent coverage!"
              } else if (p+0 >= 70) {
                print "👍 Good coverage!"
              }
            }
          }'

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: coverage.out
          retention-days: 30

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4  
        with:
          name: backend-coverage-html
          path: coverage.html
          retention-days: 30