name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"

jobs:
  node:
    name: Node Build, Test & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type checking
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests (CI mode)
        run: npm test -- --reporter=verbose --run --coverage

      - name: Build for production
        run: npm run build

      - name: Check build output
        run: |
          echo "Build completed successfully!"
          echo "Build size:"
          du -sh dist/
          echo "Build contents:"
          find dist/ -type f -name "*.js" -o -name "*.css" -o -name "*.html" | head -10

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/
          retention-days: 30

      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/
          retention-days: 30