name: golangci-lint

on:
  pull_request:
    paths:
      - "**/*.go"
      - ".golangci.yml"
      - ".github/workflows/golangci-lint.yml"
      - "go.mod"
      - "go.sum"
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - ".golangci.yml"
      - ".github/workflows/golangci-lint.yml"
      - "go.mod"
      - "go.sum"

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m --verbose
